// Recovery snapshot: the live SHA-256 verifier is intentionally not committed to the public repository.
const EXPECTED_TOKEN_HASH = "__RECOVERY_REDACTED_RUNTIME_TOKEN_SHA256__";
function json(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function fail(code: string, status = 400, detail?: unknown) { return json({ ok: false, error: { code, detail: detail ?? null } }, status); }
async function sha256(value: string) { const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join(""); }
async function call(url:string, service:string, body:unknown){const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${service}`,"Content-Type":"application/json"},body:JSON.stringify(body)});return {status:r.status,ok:r.ok,body:await r.json().catch(()=>null)};}
Deno.serve(async req=>{
 if(req.method!=="POST")return fail("METHOD_NOT_ALLOWED",405);const supplied=req.headers.get("x-athrty-runtime-token")??"";if(!supplied||(await sha256(supplied))!==EXPECTED_TOKEN_HASH)return fail("AUTH_INVALID",401);
 const su=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!su||!service)return fail("SERVER_CONFIG_ERROR",500);let b:any;try{b=await req.json()}catch{return fail("INVALID_JSON")};const owner=typeof b?.owner_user_id==="string"?b.owner_user_id.trim():"";if(!owner)return fail("OWNER_REQUIRED");const queries=(Array.isArray(b?.queries)?b.queries:[]).filter((x:any)=>typeof x==="string"&&x.trim()).slice(0,3);if(!queries.length)return fail("QUERIES_REQUIRED");const pageSize=Math.min(10,Math.max(3,Number(b?.page_size)||6));const provider=typeof b?.provider==="string"?b.provider.trim():"auto";const results:any[]=[];
 for(const query of queries){try{if(provider==="web"){const w=await call(`${su}/functions/v1/prospect-discover-web`,service,{owner_user_id:owner,query,max_results:pageSize});results.push({query,provider:"openai_web_search",status:w.status,ok:w.ok&&!!w.body?.ok,result:w.body});continue;}const g=await call(`${su}/functions/v1/prospect-discover-google`,service,{owner_user_id:owner,action:"discover",query,page_size:pageSize});if(g.ok&&g.body?.ok){results.push({query,provider:"google_places",status:g.status,ok:true,result:g.body});continue;}if(provider==="google"){results.push({query,provider:"google_places",status:g.status,ok:false,google_error:g.body?.error??g.body});continue;}const code=g.body?.error?.code||"GOOGLE_FAILED";const fallbackAllowed=["GOOGLE_PLACES_NOT_CONFIGURED","GOOGLE_PLACES_SOFT_CAP_REACHED","DISCOVERY_FAILED"].includes(code);if(!fallbackAllowed){results.push({query,provider:"google_places",status:g.status,ok:false,google_error:g.body?.error??g.body});continue;}const w=await call(`${su}/functions/v1/prospect-discover-web`,service,{owner_user_id:owner,query,max_results:pageSize});results.push({query,provider:w.ok&&w.body?.ok?"openai_web_search":"none",status:w.status,ok:w.ok&&!!w.body?.ok,google_error:g.body?.error??g.body,web_result:w.body});}catch(e:any){results.push({query,provider:"none",status:0,ok:false,error:String(e?.message||e).slice(0,800)})}}
 const succeeded=results.filter(x=>x.ok).length;return json({ok:succeeded>0,total:results.length,succeeded,failed:results.length-succeeded,requested_provider:provider,results},succeeded>0?200:502);
});