import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const GRAPH="https://graph.microsoft.com/v1.0";
const SENDER_EMAIL="hello@athrty.co";
const BOOKING_URL="https://outlook.office.com/bookwithme/user/6a7dbda3c590477e86f11a691d2631cf@athrty.co?anonymous&ep=signature&ismsaljsauthenabled";
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(code:string,status=400,detail?:unknown){return json({ok:false,error:{code,detail:detail??null}},status)}
function txt(v:unknown){return typeof v==="string"?v.trim():""}
function env(k:string){return Deno.env.get(k)?.trim()||null}
function validEmail(s:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}
function cleanPostal(v:string){return v.replace(/^\s*OUTREACH_POSTAL_ADDRESS\s*=\s*/i,"").trim()}
function cleanEmailText(v:string){return v.replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,"-").replace(/·/g,"|").replace(/\u00a0/g," ").replace(/[\u200B\u200C\u200D\uFEFF]/g,"").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n")}
function signatureHtml(){return `<div style="margin-top:22px;padding-top:14px;border-top:1px solid #e5e7eb;font-family:Arial,sans-serif;color:#111827"><div style="font-size:13px;font-weight:700;letter-spacing:.08em">ATHRTY SYSTEMS</div><div style="font-size:12px;margin-top:4px"><a href="https://athrty.co" style="color:#111827;text-decoration:none;font-weight:600">ATHRTY.CO</a></div><div style="font-size:11px;color:#6b7280;margin-top:4px">Start with clarity. Build with structure.</div><div style="font-size:11px;margin-top:8px"><a href="${BOOKING_URL}" style="color:#374151">Book time to meet</a></div></div>`}
function commercialHtml(text:string,postalRaw:string){const postal=cleanEmailText(cleanPostal(postalRaw));const body=esc(cleanEmailText(text)).replace(/\n/g,"<br>");return `<div style="font-family:Arial,sans-serif;font-size:15px;line-height:1.55;color:#111827">${body}${signatureHtml()}<div style="font-size:10px;line-height:1.4;color:#9ca3af;margin-top:14px;padding-top:10px;border-top:1px solid #e5e7eb">ATHRTY | ${esc(postal)}<br>Reply &quot;unsubscribe&quot; or &quot;no thanks&quot; to stop future emails.</div></div>`}
function qualityScore(item:any,profile:any,contact:any){const body=String(item.body||"");let specificity=45;if(item.evidence_claim&&item.evidence_url)specificity+=20;if(profile?.organizations?.name&&body.toLowerCase().includes(String(profile.organizations.name).toLowerCase()))specificity+=5;if(body.includes("?"))specificity+=8;if(body.length>=120&&body.length<=700)specificity+=7;if(!/cutting-edge|revolutionary|synergy|just checking in|circle back|touch base|leverage|optimize|transform/i.test(body))specificity+=8;if(contact?.contact_type==="decision_maker")specificity+=7;specificity=Math.min(100,specificity);const evidence=Number(profile?.evidence_quality_score)||Number(item.evidence_quality_score)||0;const contactQ=Number(contact?.contact_quality_score)||Number(item.contact_quality_score)||0;const message=Math.min(100,specificity*0.55+evidence*0.25+contactQ*0.20);return {specificity,message,evidence,contactQ}}
async function token(){const tenant=env("M365_TENANT_ID"),client=env("M365_CLIENT_ID"),secret=env("M365_CLIENT_SECRET");if(!tenant||!client||!secret)throw new Error("m365_configuration_missing");const r=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:client,client_secret:secret,grant_type:"client_credentials",scope:"https://graph.microsoft.com/.default"})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.access_token)throw new Error("microsoft_auth_failed");return j.access_token as string}
async function graph(t:string,path:string,init:RequestInit){const r=await fetch(`${GRAPH}${path}`,{...init,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(init.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(`graph_http_${r.status}:${text.slice(0,500)}`);return text}
async function ctx(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.toLowerCase().startsWith("bearer "))throw Object.assign(new Error("AUTH_REQUIRED"),{status:401});const su=env("SUPABASE_URL"),anon=env("SUPABASE_ANON_KEY"),service=env("SUPABASE_SERVICE_ROLE_KEY");if(!su||!anon||!service)throw Object.assign(new Error("SERVER_CONFIG_ERROR"),{status:500});const ac=createClient(su,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const u=await ac.auth.getUser();if(u.error||!u.data.user?.id)throw Object.assign(new Error("AUTH_INVALID"),{status:401});return {owner:u.data.user.id,db:createClient(su,service,{auth:{persistSession:false}})}}
async function itemContext(db:any,owner:string,id:string){const q=await db.from("prospect_outreach_queue").select("*,prospect_profiles(*,organizations(name)),prospect_contact_candidates(*),prospect_outreach_reviews(*)").eq("id",id).eq("owner_user_id",owner).maybeSingle();if(q.error||!q.data)throw Object.assign(new Error("QUEUE_ITEM_NOT_FOUND"),{status:404,detail:q.error?.message});return q.data}
async function policyFor(db:any,owner:string,brand:string){const p=await db.from("prospect_outreach_policies").select("*").eq("owner_user_id",owner).eq("brand_key",brand).eq("active",true).maybeSingle();if(p.error||!p.data)throw Object.assign(new Error("ACTIVE_POLICY_REQUIRED"),{status:409,detail:p.error?.message});return p.data}
async function suppressAll(db:any,owner:string,item:any,reason:string,source:string){const profile=item.prospect_profiles,contact=item.prospect_contact_candidates,email=String(contact?.email||"").toLowerCase(),domain=String(profile?.canonical_domain||"").toLowerCase();if(email)await db.from("outreach_suppressions").upsert({owner_user_id:owner,email_normalized:email,reason,source},{onConflict:"owner_user_id,email_normalized"});if(domain)await db.from("outreach_suppressions").upsert({owner_user_id:owner,domain_normalized:domain,reason,source},{onConflict:"owner_user_id,domain_normalized"});await db.from("prospect_outreach_queue").update({state:"suppressed",updated_at:new Date().toISOString()}).eq("owner_user_id",owner).eq("prospect_profile_id",item.prospect_profile_id).in("state",["draft","review","approved","scheduled","nurture","failed"]);await db.from("prospect_profiles").update({suppress_outreach:true,suppression_reason:reason,outreach_status:"suppressed",updated_at:new Date().toISOString()}).eq("id",item.prospect_profile_id)}
Deno.serve(async req=>{
 if(req.method!=="POST")return fail("METHOD_NOT_ALLOWED",405);let c;try{c=await ctx(req)}catch(e:any){return fail(e.message,e.status||500,e.detail)}const {owner,db}=c;let b:any;try{b=await req.json()}catch{return fail("INVALID_JSON")};const action=txt(b?.action);
 try{
  if(action==="list_queue"){const states=Array.isArray(b?.states)&&b.states.length?b.states:["draft","review","approved","scheduled","nurture"];const r=await db.from("prospect_outreach_queue").select("*,prospect_profiles(id,organization_id,canonical_domain,website,summary,overall_score,athrty_fit_score,evidence_quality_score,outreach_readiness_score,commercial_priority_score,source_coverage_count,outreach_status,outreach_eligibility,suppress_outreach,organizations(name)),prospect_contact_candidates(id,name,email,phone,job_title,role_class,contact_type,source_url,verification_status,confidence,decision_maker_score,contact_quality_score,outreach_eligible)").eq("owner_user_id",owner).in("state",states).order("created_at",{ascending:true}).limit(Math.min(100,Math.max(1,Number(b?.limit)||50)));if(r.error)throw r.error;return json({ok:true,data:r.data||[]})}
  const id=txt(b?.queue_id);if(!id)return fail("QUEUE_ID_REQUIRED");const item:any=await itemContext(db,owner,id);const profile:any=item.prospect_profiles,contact:any=item.prospect_contact_candidates;const policy:any=await policyFor(db,owner,item.brand_key);
  if(action==="review_draft"){if(!["draft","review"].includes(item.state))return fail("QUEUE_ITEM_NOT_REVIEWABLE",409,{state:item.state});const subject=cleanEmailText(txt(b?.subject)||item.subject),body=cleanEmailText(txt(b?.body)||item.body);if(!subject||!body)return fail("SUBJECT_AND_BODY_REQUIRED");const scores=qualityScore({...item,subject,body},profile,contact);const profileFit=Number(profile.athrty_fit_score)||0;const reasons:string[]=[];if(Number(profile.overall_score)<Number(policy.min_overall_score))reasons.push("overall_score_below_threshold");if(profileFit<Number(policy.min_brand_fit_score))reasons.push("brand_fit_below_threshold");if(Number(profile.confidence)<Number(policy.min_confidence))reasons.push("profile_confidence_below_threshold");if(Number(profile.evidence_quality_score)<Number(policy.min_evidence_quality_score))reasons.push("evidence_quality_below_threshold");if(Number(profile.source_coverage_count)<Number(policy.min_source_coverage))reasons.push("source_coverage_below_threshold");if(!contact?.outreach_eligible)reasons.push("contact_not_outreach_eligible");if(!["public_site","verified"].includes(contact?.verification_status))reasons.push("contact_not_publicly_verified");if(scores.contactQ<Number(policy.min_contact_quality_score))reasons.push("contact_quality_below_threshold");if(scores.specificity<75)reasons.push("message_specificity_below_threshold");if(scores.message<Number(policy.min_message_quality_score))reasons.push("message_quality_below_threshold");if((body.match(/\?/g)||[]).length!==1)reasons.push("one_question_required");if(body.split(/\s+/).length>90)reasons.push("message_too_long_for_athrty_standard");if(/[’‘“”·–—]/.test(subject+body))reasons.push("nonstandard_punctuation_not_allowed");const passed=reasons.length===0;const update:any={subject,body,message_quality_score:scores.message,specificity_score:scores.specificity,contact_quality_score:scores.contactQ,evidence_quality_score:scores.evidence,policy_passed:passed,policy_reasons:passed?["premium_policy_passed","plain_language_passed","punctuation_normalized","human_review_required"]:reasons,state:passed?"review":"draft",updated_at:new Date().toISOString()};const r=await db.from("prospect_outreach_queue").update(update).eq("id",id).eq("owner_user_id",owner).select("*").single();if(r.error)throw r.error;await db.from("prospect_outreach_reviews").insert({owner_user_id:owner,outreach_queue_id:id,review_status:passed?"pending":"rejected",reviewer_type:"quality_gate",quality_score:scores.message,specificity_score:scores.specificity,evidence_alignment_score:scores.evidence,brand_tone_score:90,compliance_score:100,reasons:passed?["Tight, plain-language ATHRTY email ready for human review; punctuation normalized"]:reasons,reviewed_at:new Date().toISOString()});return json({ok:true,passed,item:r.data,scores,reasons})}
  if(action==="approve"){if(item.state!=="review")return fail("QUEUE_ITEM_NOT_REVIEWABLE",409,{state:item.state});if(!item.policy_passed)return fail("PREMIUM_POLICY_NOT_MET",409,{reasons:item.policy_reasons});const now=new Date().toISOString();const r=await db.from("prospect_outreach_queue").update({state:"approved",human_approved_at:now,human_approved_by:owner,updated_at:now}).eq("id",id).eq("owner_user_id",owner).select("*").single();if(r.error)throw r.error;await db.from("prospect_outreach_reviews").insert({owner_user_id:owner,outreach_queue_id:id,review_status:"approved",reviewer_type:"human",reviewer_id:owner,quality_score:item.message_quality_score,specificity_score:item.specificity_score,evidence_alignment_score:item.evidence_quality_score,brand_tone_score:95,compliance_score:100,reasons:["Human approved curated one-to-one ATHRTY outreach"],reviewed_at:now});return json({ok:true,item:r.data})}
  if(action==="suppress"||action==="opt_out"){const reason=txt(b?.reason)||(action==="opt_out"?"recipient_opt_out":"manual_suppression");await suppressAll(db,owner,item,reason,action==="opt_out"?"recipient_reply":"manual");return json({ok:true,suppressed:true,reason})}
  if(action==="mark_replied"){const now=new Date().toISOString();await db.from("prospect_outreach_queue").update({state:"replied",replied_at:now,updated_at:now}).eq("id",id).eq("owner_user_id",owner);await db.from("prospect_outreach_queue").update({state:"cancelled",updated_at:now}).eq("owner_user_id",owner).eq("prospect_profile_id",item.prospect_profile_id).in("state",["draft","review","approved","scheduled","nurture"]);await db.from("prospect_profiles").update({outreach_status:"responded",updated_at:now}).eq("id",item.prospect_profile_id);return json({ok:true,replied:true,sequence_stopped:true})}
  if(action!=="send_one")return fail("INVALID_ACTION");
  if(!["approved","scheduled"].includes(item.state))return fail("QUEUE_ITEM_NOT_APPROVED",409,{state:item.state});if(!item.policy_passed)return fail("PREMIUM_POLICY_NOT_MET",409,{reasons:item.policy_reasons});if(!item.human_approved_at)return fail("HUMAN_APPROVAL_REQUIRED",409);if(item.send_after&&new Date(item.send_after).getTime()>Date.now())return fail("SEND_NOT_DUE",409,{send_after:item.send_after});if(profile.suppress_outreach||profile.outreach_status==="suppressed")return fail("PROSPECT_SUPPRESSED",409);if(!contact?.outreach_eligible||!["public_site","verified"].includes(contact?.verification_status))return fail("CONTACT_NOT_ELIGIBLE",409);
  const email=txt(contact.email).toLowerCase();if(!validEmail(email))return fail("VALID_PUBLIC_EMAIL_REQUIRED",409);const postal=env("OUTREACH_POSTAL_ADDRESS");if(!postal)return fail("OUTREACH_POSTAL_ADDRESS_REQUIRED",503);
  const es=await db.from("outreach_suppressions").select("id").eq("owner_user_id",owner).eq("email_normalized",email).maybeSingle();const ds=await db.from("outreach_suppressions").select("id").eq("owner_user_id",owner).eq("domain_normalized",profile.canonical_domain).maybeSingle();if(es.data||ds.data)return fail("CONTACT_SUPPRESSED",409);
  const start=new Date();start.setUTCHours(0,0,0,0);const totalToday=await db.from("prospect_outreach_queue").select("id",{count:"exact",head:true}).eq("owner_user_id",owner).eq("state","sent").gte("sent_at",start.toISOString());if((totalToday.count||0)>=Number(policy.max_total_outreach_per_day))return fail("TOTAL_DAILY_CAP_REACHED",429,{cap:policy.max_total_outreach_per_day});if(item.sequence_step===1){const initialToday=await db.from("prospect_outreach_queue").select("id",{count:"exact",head:true}).eq("owner_user_id",owner).eq("state","sent").eq("sequence_step",1).gte("sent_at",start.toISOString());if((initialToday.count||0)>=Number(policy.max_initial_outreach_per_day))return fail("INITIAL_DAILY_CAP_REACHED",429,{cap:policy.max_initial_outreach_per_day})}
  const sentHistory=await db.from("prospect_outreach_queue").select("id,sent_at,sequence_step,replied_at").eq("owner_user_id",owner).eq("prospect_profile_id",item.prospect_profile_id).eq("state","sent").order("sent_at",{ascending:false});if((sentHistory.data||[]).length>=Number(policy.max_touches_per_organization))return fail("MAX_TOUCHES_REACHED",429,{max:policy.max_touches_per_organization});const last=(sentHistory.data||[])[0];if(last?.sent_at){const nextAllowed=new Date(new Date(last.sent_at).getTime()+Number(policy.min_days_between_touches)*86400000);if(nextAllowed.getTime()>Date.now())return fail("ORGANIZATION_COOLDOWN_ACTIVE",429,{next_allowed_at:nextAllowed.toISOString()})}
  const approvedAt=new Date(item.human_approved_at);if(!Number.isFinite(approvedAt.getTime())||Date.now()-approvedAt.getTime()>7*86400000)return fail("APPROVAL_EXPIRED",409);
  await db.from("prospect_outreach_queue").update({state:"sending",opt_out_included:true,postal_address_included:true,commercial_disclosure_version:"can_spam_footer_v4_ascii",updated_at:new Date().toISOString()}).eq("id",id);
  try{const t=await token();const payload={message:{subject:cleanEmailText(item.subject),body:{contentType:"HTML",content:commercialHtml(item.body,postal)},from:{emailAddress:{address:SENDER_EMAIL}},sender:{emailAddress:{address:SENDER_EMAIL}},replyTo:[{emailAddress:{address:SENDER_EMAIL}}],toRecipients:[{emailAddress:{address:email,name:contact.name||undefined}}]},saveToSentItems:true};await graph(t,`/users/${encodeURIComponent(SENDER_EMAIL)}/sendMail`,{method:"POST",body:JSON.stringify(payload)});const sentAt=new Date().toISOString();await db.from("prospect_outreach_queue").update({state:"sent",sent_at:sentAt,failure_code:null,failure_message:null,updated_at:sentAt,metadata:{...(item.metadata||{}),requested_sender:SENDER_EMAIL,server_signature_version:"athrty_signature_v2_ascii",punctuation_normalized:true}}).eq("id",id);await db.from("prospect_profiles").update({outreach_status:"contacted",updated_at:sentAt}).eq("id",profile.id);
   const nextStep=Number(item.sequence_step)+1;if(nextStep<=Number(policy.max_touches_per_organization)){const idem=`prospect:${profile.id}:${item.brand_key}:${item.sequence_key}:${nextStep}`;const followSubject=cleanEmailText(item.subject.toLowerCase().startsWith("re:")?item.subject:`Re: ${item.subject}`);const first=(contact.name||"").split(/\s+/)[0];const greeting=first?`Hi ${first},`:`Hi,`;const followBody=cleanEmailText(`${greeting}\n\nOne quick follow-up. Is there one step in the process your team still has to do by hand that should be easier?`);await db.from("prospect_outreach_queue").upsert({owner_user_id:owner,prospect_profile_id:profile.id,contact_candidate_id:contact.id,engagement_id:item.engagement_id,brand_key:item.brand_key,sequence_key:item.sequence_key,sequence_step:nextStep,state:"draft",evidence_url:item.evidence_url,evidence_claim:item.evidence_claim,subject:followSubject,body:followBody,rationale:"One short plain-language follow-up; human review required before send.",send_after:new Date(Date.now()+Number(policy.min_days_between_touches)*86400000).toISOString(),idempotency_key:idem,message_quality_score:0,specificity_score:0,contact_quality_score:Number(contact.contact_quality_score)||0,evidence_quality_score:Number(profile.evidence_quality_score)||0,policy_passed:false,policy_reasons:["follow_up_requires_quality_review","human_review_required"],metadata:{parent_queue_id:id,composer:"athrty-two-angle-v1",no_em_dash:true,manual_signature_removed:true,punctuation_normalized:true}},{onConflict:"owner_user_id,idempotency_key"})}
   return json({ok:true,sent:true,queue_id:id,to:email,from:SENDER_EMAIL,sent_at:sentAt,next_touch_draft_created:nextStep<=Number(policy.max_touches_per_organization)})
  }catch(e:any){await db.from("prospect_outreach_queue").update({state:"failed",failure_code:"SEND_FAILED",failure_message:String(e?.message||e).slice(0,1200),updated_at:new Date().toISOString()}).eq("id",id);return fail("SEND_FAILED",502,String(e?.message||e).slice(0,1200))}
 }catch(e:any){return fail("PROSPECT_OUTREACH_FAILED",e?.status||500,e?.detail||String(e?.message||e).slice(0,1500))}
});