"""Generate deterministic launchers pointing at the pinned installation.

Launchers themselves are generated (ephemeral) files outside Git; only this
generator is source-controlled.
"""

from __future__ import annotations

import stat
import sys
from pathlib import Path

JARVIS_LAUNCHER_TEMPLATE = """#!/bin/sh
# Generated by runtime/bootstrap/generate_launchers.py — do not edit by hand.
export OPENJARVIS_HOME="{openjarvis_home}"
exec "{router_wrapper}" "$@"
"""

CASH_MCP_LAUNCHER_TEMPLATE = """#!/bin/sh
# Generated by runtime/bootstrap/generate_launchers.py — do not edit by hand.
export PYTHONPATH="{cash_mcp_src}:$PYTHONPATH"
exec "{python_bin}" -m cash_mcp_main "$@"
"""


def _write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink() or path.exists():
        path.unlink()
    path.write_text(content, encoding="utf-8")
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def generate_jarvis_launcher(
    jarvis_bin: Path,
    *,
    launcher_path: Path,
    openjarvis_home: Path = Path("~/.openjarvis").expanduser(),
) -> Path:
    content = JARVIS_LAUNCHER_TEMPLATE.format(
        openjarvis_home=str(openjarvis_home), jarvis_bin=str(jarvis_bin)
    )
    _write_executable(launcher_path, content)
    return launcher_path


def generate_cash_mcp_launcher(
    cash_mcp_src: Path,
    *,
    launcher_path: Path,
    python_bin: Path = Path(sys.executable),
) -> Path:
    content = CASH_MCP_LAUNCHER_TEMPLATE.format(
        cash_mcp_src=str(cash_mcp_src), python_bin=str(python_bin)
    )
    _write_executable(launcher_path, content)
    return launcher_path
