import { createClient } from "npm:@supabase/supabase-js@2.57.4";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(code:string,status=400,detail?:unknown){return json({ok:false,error:{code,detail:detail??null}},status)}
function txt(v:unknown){return typeof v==="string"?v.trim():""}
function clamp(v:number,min=0,max=100){return Math.max(min,Math.min(max,Number.isFinite(v)?v:0))}
function emailLocal(email:string){return (email.split("@")[0]||"").toLowerCase()}
const generic=/^(info|hello|contact|office|admin|support|service|sales|team|quotes?|estimating|appointments?|booking|customerservice)$/i;
function roleClass(title:string,name:string,email:string){const x=`${title} ${name}`.toLowerCase();if(/owner|founder|president|principal|partner/.test(x))return "owner";if(/chief|ceo|coo|cmo|cto|vp|vice president|director/.test(x))return "executive";if(/marketing|brand|creative/.test(x))return "marketing_leader";if(/operations|general manager|office manager/.test(x))return "operations_leader";if(/sales|business development/.test(x))return "sales_leader";if(generic.test(emailLocal(email)))return "department";return "unknown"}
function dmScore(role:string,type:string){if(role==="owner")return 98;if(role==="executive")return 92;if(["operations_leader","marketing_leader","sales_leader"].includes(role))return 86;if(type==="decision_maker")return 82;if(type==="department")return 35;return 50}
function contactQuality(role:string,type:string,confidence:number,sourceCount:number,email:string){let q=confidence*60+Math.min(15,sourceCount*5);if(role==="owner"||role==="executive")q+=25;else if(role.endsWith("_leader"))q+=20;else if(type==="business")q+=10;else if(type==="department")q+=4;if(/^(info|hello|contact|admin)@/i.test(email))q-=15;return clamp(q)}
function sourceRows(input:any){return (Array.isArray(input)?input:[]).map((s:any)=>({channel_type:txt(s?.channel_type)||"other",url:txt(s?.url),handle:txt(s?.handle)||null,audience_size:Number.isFinite(Number(s?.audience_size))?Number(s.audience_size):null,review_count:Number.isFinite(Number(s?.review_count))?Number(s.review_count):null,rating:Number.isFinite(Number(s?.rating))?Number(s.rating):null,post_count_90d:Number.isFinite(Number(s?.post_count_90d))?Number(s.post_count_90d):null,activity_recency_score:clamp(Number(s?.activity_recency_score)||0),content_quality_score:clamp(Number(s?.content_quality_score)||0),engagement_signal_score:clamp(Number(s?.engagement_signal_score)||0),market_visibility_score:clamp(Number(s?.market_visibility_score)||0),provider:txt(s?.provider)||null,traffic_metric:txt(s?.traffic_metric)||null,traffic_value:Number.isFinite(Number(s?.traffic_value))?Number(s.traffic_value):null,traffic_provider:txt(s?.traffic_provider)||null,observed_text:txt(s?.observed_text)||null,contacts:Array.isArray(s?.contacts)?s.contacts:[]})).filter((s:any)=>s.url)}
Deno.serve(async req=>{
 if(req.method!=="POST")return fail("METHOD_NOT_ALLOWED",405);const auth=req.headers.get("authorization")||"";if(!auth.toLowerCase().startsWith("bearer "))return fail("AUTH_REQUIRED",401);
 const su=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!su||!anon||!service)return fail("SERVER_CONFIG_ERROR",500);
 const ac=createClient(su,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const ur=await ac.auth.getUser();if(ur.error||!ur.data.user?.id)return fail("AUTH_INVALID",401);const owner=ur.data.user.id;const db=createClient(su,service,{auth:{persistSession:false}});
 let b:any;try{b=await req.json()}catch{return fail("INVALID_JSON")};const profileId=txt(b?.prospect_profile_id);if(!profileId)return fail("PROSPECT_PROFILE_ID_REQUIRED");const sources=sourceRows(b?.public_sources);
 try{
  const pr=await db.from("prospect_profiles").select("*").eq("id",profileId).eq("owner_user_id",owner).maybeSingle();if(pr.error||!pr.data)return fail("PROFILE_NOT_FOUND",404,pr.error?.message);const p:any=pr.data;
  const org=await db.from("organizations").select("*").eq("id",p.organization_id).maybeSingle();const ev=await db.from("prospect_evidence").select("*").eq("prospect_profile_id",profileId).order("observed_at",{ascending:false});const currentContacts=await db.from("prospect_contact_candidates").select("*").eq("prospect_profile_id",profileId);
  for(const s of sources){await db.from("prospect_channel_profiles").upsert({owner_user_id:owner,prospect_profile_id:profileId,channel_type:s.channel_type,canonical_url:s.url,handle:s.handle,source_public:true,source_status:"observed",audience_size:s.audience_size,review_count:s.review_count,rating:s.rating,post_count_90d:s.post_count_90d,activity_recency_score:s.activity_recency_score,content_quality_score:s.content_quality_score,engagement_signal_score:s.engagement_signal_score,market_visibility_score:s.market_visibility_score,evidence:{source_label:s.provider||s.channel_type,provider:s.provider,observed_text:s.observed_text,traffic_metric:s.traffic_metric,traffic_value:s.traffic_value,traffic_provider:s.traffic_provider},last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"owner_user_id,prospect_profile_id,channel_type,canonical_url"});
   for(const c of s.contacts){const email=txt(c?.email).toLowerCase();if(!email)continue;const name=txt(c?.name)||emailLocal(email),job=txt(c?.job_title),type=job?"decision_maker":(generic.test(emailLocal(email))?"department":"business"),role=roleClass(job,name,email),confidence=Math.max(0,Math.min(1,Number(c?.confidence)||0.9)),existing=(currentContacts.data||[]).find((x:any)=>String(x.email||"").toLowerCase()===email),sourceCount=Math.max(Number(existing?.source_count)||1,2),quality=contactQuality(role,type,confidence,sourceCount,email),outreachEligible=quality>=72&&(type==="decision_maker"||!generic.test(emailLocal(email)));const payload={owner_user_id:owner,prospect_profile_id:profileId,organization_id:p.organization_id,name,job_title:job||null,email,phone:txt(c?.phone)||null,contact_type:type,source_url:txt(c?.source_url)||s.url,source_label:txt(c?.source_label)||`Public ${s.channel_type} source`,confidence,verification_status:"verified",seniority:txt(c?.seniority)||null,role_class:role,decision_maker_score:dmScore(role,type),contact_quality_score:quality,source_count:sourceCount,profile_urls:[s.url],bio_summary:txt(c?.bio_summary)||null,last_verified_at:new Date().toISOString(),outreach_eligible:outreachEligible,eligibility_reason:outreachEligible?"public_role_evidence":"insufficient_contact_quality",updated_at:new Date().toISOString()};if(existing)await db.from("prospect_contact_candidates").update(payload).eq("id",existing.id);else await db.from("prospect_contact_candidates").insert(payload)}
   if(s.review_count!=null)await db.from("prospect_market_signals").insert({owner_user_id:owner,prospect_profile_id:profileId,signal_type:"reputation",signal_key:"review_count",numeric_value:s.review_count,confidence:0.9,source_type:s.channel_type,source_url:s.url});if(s.rating!=null)await db.from("prospect_market_signals").insert({owner_user_id:owner,prospect_profile_id:profileId,signal_type:"reputation",signal_key:"rating",numeric_value:s.rating,confidence:0.9,source_type:s.channel_type,source_url:s.url});
  }
  const channels=await db.from("prospect_channel_profiles").select("*").eq("prospect_profile_id",profileId);const contacts=await db.from("prospect_contact_candidates").select("*").eq("prospect_profile_id",profileId).order("outreach_eligible",{ascending:false}).order("decision_maker_score",{ascending:false}).order("contact_quality_score",{ascending:false});const market=await db.from("prospect_market_signals").select("*").eq("prospect_profile_id",profileId);const providers=await db.from("prospect_provider_snapshots").select("provider_key,provider_status,observed_at").eq("prospect_profile_id",profileId).in("provider_status",["complete","partial"]);
  const cs:any[]=channels.data||[],ct:any[]=contacts.data||[],ms:any[]=market.data||[],ps:any[]=providers.data||[];const sourceTypes=new Set(["website",...cs.map(x=>x.channel_type),...sources.map(x=>x.channel_type),...ps.map(x=>`provider:${x.provider_key}`)]);const sourceCoverage=sourceTypes.size;const namedDM=ct.filter(x=>x.contact_type==="decision_maker"&&x.outreach_eligible).length;const publicContacts=ct.filter(x=>["public_site","verified"].includes(x.verification_status)).length;const bestContact=ct[0]||null,bestCQ=Number(bestContact?.contact_quality_score)||0;
  const reviewCount=cs.reduce((n,x)=>n+(Number(x.review_count)||0),0),ratings=cs.filter(x=>Number.isFinite(Number(x.rating))).map(x=>Number(x.rating)),avgRating=ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null;const channelPresence=clamp(cs.length*11+Math.min(25,cs.reduce((n,x)=>n+(Number(x.activity_recency_score)||0),0)/Math.max(1,cs.length)*0.25));const reputation=clamp((avgRating?Math.max(0,(avgRating-3)*22):15)+Math.min(55,Math.log10(Math.max(1,reviewCount))*22));const publicVisibility=clamp(channelPresence*0.5+reputation*0.35+Math.min(15,sources.length*3));const providerVis=ms.filter(x=>x.signal_key==="provider_market_visibility_score"&&String(x.source_type||"").startsWith("provider:")).sort((a,b)=>new Date(b.observed_at).getTime()-new Date(a.observed_at).getTime())[0];const visibility=providerVis?clamp(Number(providerVis.numeric_value)||0):publicVisibility;const trafficBacked=ms.some(x=>x.signal_type==="traffic"&&String(x.source_type||"").startsWith("provider:"));const evidenceQuality=clamp(30+Math.min(25,(ev.data||[]).length*3)+Math.min(35,sourceCoverage*8)+(namedDM?10:0));const routedBrand=p.best_fit==="truett-cash"?"truett-cash":"authority-systems",routedFit=Number(routedBrand==="truett-cash"?p.truett_fit_score:p.athrty_fit_score)||0;const readiness=clamp(routedFit*0.28+Number(p.overall_score||0)*0.18+evidenceQuality*0.22+bestCQ*0.18+Number(p.confidence||0)*100*0.14);const priority=clamp(routedFit*0.38+Number(p.overall_score||0)*0.22+evidenceQuality*0.20+bestCQ*0.12+visibility*0.08);
  const pol=await db.from("prospect_outreach_policies").select("*").eq("owner_user_id",owner).eq("brand_key",routedBrand).eq("active",true).maybeSingle();const policy:any=pol.data;const roleOk=bestContact&&(bestContact.contact_type==="decision_maker"||["owner","founder","executive","marketing_leader","operations_leader","sales_leader"].includes(bestContact.role_class)||((bestContact.contact_type==="business"||bestContact.contact_type==="department")&&Number(p.overall_score)>=Number(policy?.generic_inbox_min_overall_score||88)&&sourceCoverage>=Number(policy?.generic_inbox_min_source_coverage||4)));const eligible=!!policy&&!p.suppress_outreach&&Number(p.overall_score)>=Number(policy.min_overall_score)&&routedFit>=Number(policy.min_brand_fit_score)&&Number(p.confidence)>=Number(policy.min_confidence)&&evidenceQuality>=Number(policy.min_evidence_quality_score)&&sourceCoverage>=Number(policy.min_source_coverage)&&bestContact?.outreach_eligible&&bestCQ>=Number(policy.min_contact_quality_score)&&roleOk;const eligibility=eligible?"review_ready":(Number(p.overall_score)>=60?"research_more":"hold");const reason=eligible?"premium_policy_passed":sourceCoverage<Number(policy?.min_source_coverage||3)?"insufficient_source_coverage":!bestContact?.outreach_eligible?"no_high_quality_public_contact":evidenceQuality<Number(policy?.min_evidence_quality_score||70)?"insufficient_evidence_quality":routedFit<Number(policy?.min_brand_fit_score||72)?"brand_fit_below_threshold":"hold_for_review";
  if(!trafficBacked&&!ms.some(x=>x.signal_type==="visibility_proxy"))await db.from("prospect_market_signals").insert({owner_user_id:owner,prospect_profile_id:profileId,signal_type:"visibility_proxy",signal_key:"market_visibility_score",numeric_value:publicVisibility,confidence:0.65,source_type:"derived_public_signals",source_url:p.website,metadata:{not_actual_traffic:true}});
  const brandProfile={company_summary:p.summary||null,positioning:p.brand_profile?.positioning||null,value_proposition:p.brand_profile?.value_proposition||null,target_audiences:p.brand_profile?.target_audiences||[],services_offers:p.brand_profile?.services_offers||[],differentiators:p.brand_profile?.differentiators||[],proof_points:p.brand_profile?.proof_points||[],conversion_paths:p.brand_profile?.conversion_paths||[],operational_clues:p.brand_profile?.operational_clues||[],technology_stack:p.research?.technology||p.brand_profile?.technology_stack||[],brand_voice:p.brand_profile?.brand_voice||{},visual_maturity:{score:Number(p.brand_maturity_score)||0},reputation_summary:{score:reputation,review_count:reviewCount,average_rating:avgRating},market_presence_summary:{channel_count:cs.length,market_visibility_score:visibility,traffic_is_provider_backed:trafficBacked,provider_sources:[...new Set(ps.map(x=>x.provider_key))]},observed_strengths:p.brand_profile?.observed_strengths||[],observed_gaps:p.brand_profile?.observed_gaps||[],athrty_opportunities:p.best_fit!=="truett-cash"?[p.recommended_angle].filter(Boolean):[],truett_opportunities:p.best_fit==="truett-cash"?[p.recommended_angle].filter(Boolean):[]};
  await db.from("prospect_brand_profiles").upsert({prospect_profile_id:profileId,owner_user_id:owner,...brandProfile,last_researched_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"prospect_profile_id"});const up=await db.from("prospect_profiles").update({channel_presence_score:channelPresence,market_visibility_score:visibility,reputation_score:reputation,evidence_quality_score:evidenceQuality,outreach_readiness_score:readiness,commercial_priority_score:priority,source_coverage_count:sourceCoverage,named_decision_maker_count:namedDM,public_contact_count:publicContacts,last_researched_at:new Date().toISOString(),contact_profile:{best_contact:bestContact,contacts:ct.slice(0,10)},channel_profile:{channel_count:cs.length,channels:cs.map(x=>({channel_type:x.channel_type,url:x.canonical_url,review_count:x.review_count,rating:x.rating,audience_size:x.audience_size}))},market_profile:{market_visibility_score:visibility,reputation_score:reputation,traffic_is_provider_backed:trafficBacked,provider_sources:[...new Set(ps.map(x=>x.provider_key))]},brand_profile:brandProfile,outreach_eligibility:eligibility,outreach_eligibility_reason:reason,outreach_status:eligible?"review_ready":p.outreach_status,updated_at:new Date().toISOString()}).eq("id",profileId).select("*").single();if(up.error)throw up.error;
  const weak=await db.from("prospect_outreach_queue").select("id,state").eq("prospect_profile_id",profileId).in("state",["review","draft"]);for(const q of weak.data||[])await db.from("prospect_outreach_queue").update({state:"draft",policy_passed:false,policy_reasons:["re_evaluate_after_enrichment"],updated_at:new Date().toISOString()}).eq("id",q.id);
  return json({ok:true,profile:up.data,organization:org.data||null,contacts:{count:ct.length,named_decision_makers:namedDM,best_contact:bestContact},channels:{count:cs.length,types:[...new Set(cs.map(x=>x.channel_type))]},providers:{count:ps.length,types:[...new Set(ps.map(x=>x.provider_key))]},market:{visibility_score:visibility,reputation_score:reputation,traffic_signal:trafficBacked?"provider_backed":"visibility_proxy_only"},outreach:{eligible,eligibility,reason,readiness_score:readiness,commercial_priority_score:priority},source_coverage_count:sourceCoverage,evidence_quality_score:evidenceQuality});
 }catch(e:any){return fail("PROSPECT_ENRICH_FAILED",500,String(e?.message||e).slice(0,1500))}
});