/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedEngagementsRouteImport } from './routes/_authenticated/engagements'
import { Route as AuthenticatedDataHealthRouteImport } from './routes/_authenticated/data-health'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedAthrtyRouteImport } from './routes/_authenticated/athrty'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedIntelligenceIndexRouteImport } from './routes/_authenticated/intelligence.index'
import { Route as AuthenticatedAthrtyIndexRouteImport } from './routes/_authenticated/athrty.index'
import { Route as AuthenticatedIntelligenceReviewRouteImport } from './routes/_authenticated/intelligence.review'
import { Route as AuthenticatedIntelligenceMemoryRouteImport } from './routes/_authenticated/intelligence.memory'
import { Route as AuthenticatedIntelligenceInputsRouteImport } from './routes/_authenticated/intelligence.inputs'
import { Route as AuthenticatedIntelligenceFindingsRouteImport } from './routes/_authenticated/intelligence.findings'
import { Route as AuthenticatedBrandSlugRouteImport } from './routes/_authenticated/brand.$slug'
import { Route as AuthenticatedAthrtySyncRouteImport } from './routes/_authenticated/athrty.sync'
import { Route as AuthenticatedAthrtyPipelineRouteImport } from './routes/_authenticated/athrty.pipeline'
import { Route as AuthenticatedAthrtyNextActionsRouteImport } from './routes/_authenticated/athrty.next-actions'
import { Route as AuthenticatedAthrtyAccountsRouteImport } from './routes/_authenticated/athrty.accounts'
import { Route as AuthenticatedAdminImportsWebsiteOutboundRouteImport } from './routes/_authenticated/admin.imports.website-outbound'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsRoute =
  AuthenticatedEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataHealthRoute = AuthenticatedDataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAthrtyRoute = AuthenticatedAthrtyRouteImport.update({
  id: '/athrty',
  path: '/athrty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceIndexRoute =
  AuthenticatedIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedAthrtyIndexRoute =
  AuthenticatedAthrtyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAthrtyRoute,
  } as any)
const AuthenticatedIntelligenceReviewRoute =
  AuthenticatedIntelligenceReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceMemoryRoute =
  AuthenticatedIntelligenceMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceInputsRoute =
  AuthenticatedIntelligenceInputsRouteImport.update({
    id: '/inputs',
    path: '/inputs',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceFindingsRoute =
  AuthenticatedIntelligenceFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedBrandSlugRoute = AuthenticatedBrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAthrtySyncRoute = AuthenticatedAthrtySyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedAthrtyRoute,
} as any)
const AuthenticatedAthrtyPipelineRoute =
  AuthenticatedAthrtyPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAthrtyRoute,
  } as any)
const AuthenticatedAthrtyNextActionsRoute =
  AuthenticatedAthrtyNextActionsRouteImport.update({
    id: '/next-actions',
    path: '/next-actions',
    getParentRoute: () => AuthenticatedAthrtyRoute,
  } as any)
const AuthenticatedAthrtyAccountsRoute =
  AuthenticatedAthrtyAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAthrtyRoute,
  } as any)
const AuthenticatedAdminImportsWebsiteOutboundRoute =
  AuthenticatedAdminImportsWebsiteOutboundRouteImport.update({
    id: '/admin/imports/website-outbound',
    path: '/admin/imports/website-outbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/athrty': typeof AuthenticatedAthrtyRouteWithChildren
  '/command': typeof AuthenticatedCommandRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/engagements': typeof AuthenticatedEngagementsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/intelligence': typeof AuthenticatedIntelligenceRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/athrty/accounts': typeof AuthenticatedAthrtyAccountsRoute
  '/athrty/next-actions': typeof AuthenticatedAthrtyNextActionsRoute
  '/athrty/pipeline': typeof AuthenticatedAthrtyPipelineRoute
  '/athrty/sync': typeof AuthenticatedAthrtySyncRoute
  '/brand/$slug': typeof AuthenticatedBrandSlugRoute
  '/intelligence/findings': typeof AuthenticatedIntelligenceFindingsRoute
  '/intelligence/inputs': typeof AuthenticatedIntelligenceInputsRoute
  '/intelligence/memory': typeof AuthenticatedIntelligenceMemoryRoute
  '/intelligence/review': typeof AuthenticatedIntelligenceReviewRoute
  '/athrty/': typeof AuthenticatedAthrtyIndexRoute
  '/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/admin/imports/website-outbound': typeof AuthenticatedAdminImportsWebsiteOutboundRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/command': typeof AuthenticatedCommandRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/engagements': typeof AuthenticatedEngagementsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/athrty/accounts': typeof AuthenticatedAthrtyAccountsRoute
  '/athrty/next-actions': typeof AuthenticatedAthrtyNextActionsRoute
  '/athrty/pipeline': typeof AuthenticatedAthrtyPipelineRoute
  '/athrty/sync': typeof AuthenticatedAthrtySyncRoute
  '/brand/$slug': typeof AuthenticatedBrandSlugRoute
  '/intelligence/findings': typeof AuthenticatedIntelligenceFindingsRoute
  '/intelligence/inputs': typeof AuthenticatedIntelligenceInputsRoute
  '/intelligence/memory': typeof AuthenticatedIntelligenceMemoryRoute
  '/intelligence/review': typeof AuthenticatedIntelligenceReviewRoute
  '/athrty': typeof AuthenticatedAthrtyIndexRoute
  '/intelligence': typeof AuthenticatedIntelligenceIndexRoute
  '/admin/imports/website-outbound': typeof AuthenticatedAdminImportsWebsiteOutboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/athrty': typeof AuthenticatedAthrtyRouteWithChildren
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/data-health': typeof AuthenticatedDataHealthRoute
  '/_authenticated/engagements': typeof AuthenticatedEngagementsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/athrty/accounts': typeof AuthenticatedAthrtyAccountsRoute
  '/_authenticated/athrty/next-actions': typeof AuthenticatedAthrtyNextActionsRoute
  '/_authenticated/athrty/pipeline': typeof AuthenticatedAthrtyPipelineRoute
  '/_authenticated/athrty/sync': typeof AuthenticatedAthrtySyncRoute
  '/_authenticated/brand/$slug': typeof AuthenticatedBrandSlugRoute
  '/_authenticated/intelligence/findings': typeof AuthenticatedIntelligenceFindingsRoute
  '/_authenticated/intelligence/inputs': typeof AuthenticatedIntelligenceInputsRoute
  '/_authenticated/intelligence/memory': typeof AuthenticatedIntelligenceMemoryRoute
  '/_authenticated/intelligence/review': typeof AuthenticatedIntelligenceReviewRoute
  '/_authenticated/athrty/': typeof AuthenticatedAthrtyIndexRoute
  '/_authenticated/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/_authenticated/admin/imports/website-outbound': typeof AuthenticatedAdminImportsWebsiteOutboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/athrty'
    | '/command'
    | '/crm'
    | '/data-health'
    | '/engagements'
    | '/integrations'
    | '/intelligence'
    | '/knowledge'
    | '/portfolio'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/auth/reset-password'
    | '/athrty/accounts'
    | '/athrty/next-actions'
    | '/athrty/pipeline'
    | '/athrty/sync'
    | '/brand/$slug'
    | '/intelligence/findings'
    | '/intelligence/inputs'
    | '/intelligence/memory'
    | '/intelligence/review'
    | '/athrty/'
    | '/intelligence/'
    | '/admin/imports/website-outbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytics'
    | '/command'
    | '/crm'
    | '/data-health'
    | '/engagements'
    | '/integrations'
    | '/knowledge'
    | '/portfolio'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/auth/reset-password'
    | '/'
    | '/athrty/accounts'
    | '/athrty/next-actions'
    | '/athrty/pipeline'
    | '/athrty/sync'
    | '/brand/$slug'
    | '/intelligence/findings'
    | '/intelligence/inputs'
    | '/intelligence/memory'
    | '/intelligence/review'
    | '/athrty'
    | '/intelligence'
    | '/admin/imports/website-outbound'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/athrty'
    | '/_authenticated/command'
    | '/_authenticated/crm'
    | '/_authenticated/data-health'
    | '/_authenticated/engagements'
    | '/_authenticated/integrations'
    | '/_authenticated/intelligence'
    | '/_authenticated/knowledge'
    | '/_authenticated/portfolio'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/auth_/reset-password'
    | '/_authenticated/'
    | '/_authenticated/athrty/accounts'
    | '/_authenticated/athrty/next-actions'
    | '/_authenticated/athrty/pipeline'
    | '/_authenticated/athrty/sync'
    | '/_authenticated/brand/$slug'
    | '/_authenticated/intelligence/findings'
    | '/_authenticated/intelligence/inputs'
    | '/_authenticated/intelligence/memory'
    | '/_authenticated/intelligence/review'
    | '/_authenticated/athrty/'
    | '/_authenticated/intelligence/'
    | '/_authenticated/admin/imports/website-outbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements': {
      id: '/_authenticated/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof AuthenticatedEngagementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-health': {
      id: '/_authenticated/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof AuthenticatedDataHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athrty': {
      id: '/_authenticated/athrty'
      path: '/athrty'
      fullPath: '/athrty'
      preLoaderRoute: typeof AuthenticatedAthrtyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence/': {
      id: '/_authenticated/intelligence/'
      path: '/'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof AuthenticatedIntelligenceIndexRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/athrty/': {
      id: '/_authenticated/athrty/'
      path: '/'
      fullPath: '/athrty/'
      preLoaderRoute: typeof AuthenticatedAthrtyIndexRouteImport
      parentRoute: typeof AuthenticatedAthrtyRoute
    }
    '/_authenticated/intelligence/review': {
      id: '/_authenticated/intelligence/review'
      path: '/review'
      fullPath: '/intelligence/review'
      preLoaderRoute: typeof AuthenticatedIntelligenceReviewRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/memory': {
      id: '/_authenticated/intelligence/memory'
      path: '/memory'
      fullPath: '/intelligence/memory'
      preLoaderRoute: typeof AuthenticatedIntelligenceMemoryRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/inputs': {
      id: '/_authenticated/intelligence/inputs'
      path: '/inputs'
      fullPath: '/intelligence/inputs'
      preLoaderRoute: typeof AuthenticatedIntelligenceInputsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/findings': {
      id: '/_authenticated/intelligence/findings'
      path: '/findings'
      fullPath: '/intelligence/findings'
      preLoaderRoute: typeof AuthenticatedIntelligenceFindingsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/brand/$slug': {
      id: '/_authenticated/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof AuthenticatedBrandSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athrty/sync': {
      id: '/_authenticated/athrty/sync'
      path: '/sync'
      fullPath: '/athrty/sync'
      preLoaderRoute: typeof AuthenticatedAthrtySyncRouteImport
      parentRoute: typeof AuthenticatedAthrtyRoute
    }
    '/_authenticated/athrty/pipeline': {
      id: '/_authenticated/athrty/pipeline'
      path: '/pipeline'
      fullPath: '/athrty/pipeline'
      preLoaderRoute: typeof AuthenticatedAthrtyPipelineRouteImport
      parentRoute: typeof AuthenticatedAthrtyRoute
    }
    '/_authenticated/athrty/next-actions': {
      id: '/_authenticated/athrty/next-actions'
      path: '/next-actions'
      fullPath: '/athrty/next-actions'
      preLoaderRoute: typeof AuthenticatedAthrtyNextActionsRouteImport
      parentRoute: typeof AuthenticatedAthrtyRoute
    }
    '/_authenticated/athrty/accounts': {
      id: '/_authenticated/athrty/accounts'
      path: '/accounts'
      fullPath: '/athrty/accounts'
      preLoaderRoute: typeof AuthenticatedAthrtyAccountsRouteImport
      parentRoute: typeof AuthenticatedAthrtyRoute
    }
    '/_authenticated/admin/imports/website-outbound': {
      id: '/_authenticated/admin/imports/website-outbound'
      path: '/admin/imports/website-outbound'
      fullPath: '/admin/imports/website-outbound'
      preLoaderRoute: typeof AuthenticatedAdminImportsWebsiteOutboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAthrtyRouteChildren {
  AuthenticatedAthrtyAccountsRoute: typeof AuthenticatedAthrtyAccountsRoute
  AuthenticatedAthrtyNextActionsRoute: typeof AuthenticatedAthrtyNextActionsRoute
  AuthenticatedAthrtyPipelineRoute: typeof AuthenticatedAthrtyPipelineRoute
  AuthenticatedAthrtySyncRoute: typeof AuthenticatedAthrtySyncRoute
  AuthenticatedAthrtyIndexRoute: typeof AuthenticatedAthrtyIndexRoute
}

const AuthenticatedAthrtyRouteChildren: AuthenticatedAthrtyRouteChildren = {
  AuthenticatedAthrtyAccountsRoute: AuthenticatedAthrtyAccountsRoute,
  AuthenticatedAthrtyNextActionsRoute: AuthenticatedAthrtyNextActionsRoute,
  AuthenticatedAthrtyPipelineRoute: AuthenticatedAthrtyPipelineRoute,
  AuthenticatedAthrtySyncRoute: AuthenticatedAthrtySyncRoute,
  AuthenticatedAthrtyIndexRoute: AuthenticatedAthrtyIndexRoute,
}

const AuthenticatedAthrtyRouteWithChildren =
  AuthenticatedAthrtyRoute._addFileChildren(AuthenticatedAthrtyRouteChildren)

interface AuthenticatedIntelligenceRouteChildren {
  AuthenticatedIntelligenceFindingsRoute: typeof AuthenticatedIntelligenceFindingsRoute
  AuthenticatedIntelligenceInputsRoute: typeof AuthenticatedIntelligenceInputsRoute
  AuthenticatedIntelligenceMemoryRoute: typeof AuthenticatedIntelligenceMemoryRoute
  AuthenticatedIntelligenceReviewRoute: typeof AuthenticatedIntelligenceReviewRoute
  AuthenticatedIntelligenceIndexRoute: typeof AuthenticatedIntelligenceIndexRoute
}

const AuthenticatedIntelligenceRouteChildren: AuthenticatedIntelligenceRouteChildren =
  {
    AuthenticatedIntelligenceFindingsRoute:
      AuthenticatedIntelligenceFindingsRoute,
    AuthenticatedIntelligenceInputsRoute: AuthenticatedIntelligenceInputsRoute,
    AuthenticatedIntelligenceMemoryRoute: AuthenticatedIntelligenceMemoryRoute,
    AuthenticatedIntelligenceReviewRoute: AuthenticatedIntelligenceReviewRoute,
    AuthenticatedIntelligenceIndexRoute: AuthenticatedIntelligenceIndexRoute,
  }

const AuthenticatedIntelligenceRouteWithChildren =
  AuthenticatedIntelligenceRoute._addFileChildren(
    AuthenticatedIntelligenceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAthrtyRoute: typeof AuthenticatedAthrtyRouteWithChildren
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDataHealthRoute: typeof AuthenticatedDataHealthRoute
  AuthenticatedEngagementsRoute: typeof AuthenticatedEngagementsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBrandSlugRoute: typeof AuthenticatedBrandSlugRoute
  AuthenticatedAdminImportsWebsiteOutboundRoute: typeof AuthenticatedAdminImportsWebsiteOutboundRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAthrtyRoute: AuthenticatedAthrtyRouteWithChildren,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDataHealthRoute: AuthenticatedDataHealthRoute,
  AuthenticatedEngagementsRoute: AuthenticatedEngagementsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBrandSlugRoute: AuthenticatedBrandSlugRoute,
  AuthenticatedAdminImportsWebsiteOutboundRoute:
    AuthenticatedAdminImportsWebsiteOutboundRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
