-- ATHRTY critical current-state table DDL snapshot.
-- Generated from production catalogs during recovery pass athrty-substrate-v1.
-- Dependency-ordered for the recovered commercial control spine.
-- This is a recovery snapshot, not authorization to apply against production.

CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  website text,
  industry text,
  city text,
  state text,
  status text NOT NULL DEFAULT 'active'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  owner_user_id uuid NOT NULL,
  key text,
  CONSTRAINT "Brands_id_fkey" FOREIGN KEY (id) REFERENCES public.brands(id),
  CONSTRAINT "Brands_pkey" PRIMARY KEY (id),
  CONSTRAINT brands_owner_user_id_fk FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text,
  email text,
  phone text,
  job_title text,
  status text NOT NULL DEFAULT 'active'::text,
  source text NOT NULL DEFAULT 'manual'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL,
  organization_id uuid,
  primary_contact_id uuid,
  name text NOT NULL,
  stage text NOT NULL DEFAULT 'new'::text,
  amount numeric,
  probability numeric,
  expected_close_date date,
  lead_source text NOT NULL DEFAULT 'manual'::text,
  next_action text,
  next_action_due_at timestamp with time zone,
  lost_reason text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  value numeric,
  won_at timestamp with time zone,
  lost_at timestamp with time zone,
  closed_at timestamp with time zone,
  CONSTRAINT deals_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id),
  CONSTRAINT deals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_primary_contact_id_fkey FOREIGN KEY (primary_contact_id) REFERENCES public.contacts(id)
);

CREATE TABLE IF NOT EXISTS public.engagements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  brand_key text NOT NULL DEFAULT 'authority-systems'::text,
  submission_type text NOT NULL,
  schema_version text NOT NULL DEFAULT 'authority-intake-v1'::text,
  status text NOT NULL DEFAULT 'new'::text,
  pipeline_stage text NOT NULL DEFAULT 'intake_received'::text,
  source text,
  entry_point text,
  funnel_key text,
  intake_mode text,
  project_type text,
  priority_2 text,
  priority_3 text,
  company_name text,
  contact_name text,
  email text,
  phone text,
  qualification_score numeric,
  qualification_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  operational_brief_text text,
  operational_brief_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_submission jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  booking_confirmed boolean NOT NULL DEFAULT false,
  booking_confirmed_at timestamp with time zone,
  next_action text,
  follow_up_at timestamp with time zone,
  CONSTRAINT engagements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.engagement_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  engagement_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_type text NOT NULL,
  from_status text,
  to_status text,
  actor_type text NOT NULL,
  actor_id text,
  source text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT engagement_events_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE CASCADE,
  CONSTRAINT engagement_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prospect_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  organization_id uuid,
  canonical_domain text NOT NULL,
  website text NOT NULL,
  source_type text NOT NULL DEFAULT 'website_seed'::text,
  source_ref text,
  industry text,
  city text,
  state text,
  crawl_status text NOT NULL DEFAULT 'queued'::text,
  crawl_error text,
  last_crawled_at timestamp with time zone,
  overall_score numeric NOT NULL DEFAULT 0,
  athrty_fit_score numeric NOT NULL DEFAULT 0,
  truett_fit_score numeric NOT NULL DEFAULT 0,
  website_quality_score numeric NOT NULL DEFAULT 0,
  conversion_gap_score numeric NOT NULL DEFAULT 0,
  operations_complexity_score numeric NOT NULL DEFAULT 0,
  contactability_score numeric NOT NULL DEFAULT 0,
  confidence numeric NOT NULL DEFAULT 0,
  best_fit text NOT NULL DEFAULT 'low_fit'::text,
  recommended_offer text,
  recommended_angle text,
  recommended_next_action text,
  summary text,
  research jsonb NOT NULL DEFAULT '{}'::jsonb,
  signals jsonb NOT NULL DEFAULT '{}'::jsonb,
  outreach_status text NOT NULL DEFAULT 'unreviewed'::text,
  suppress_outreach boolean NOT NULL DEFAULT false,
  suppression_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  brand_maturity_score numeric NOT NULL DEFAULT 0,
  channel_presence_score numeric NOT NULL DEFAULT 0,
  market_visibility_score numeric NOT NULL DEFAULT 0,
  reputation_score numeric NOT NULL DEFAULT 0,
  evidence_quality_score numeric NOT NULL DEFAULT 0,
  outreach_readiness_score numeric NOT NULL DEFAULT 0,
  commercial_priority_score numeric NOT NULL DEFAULT 0,
  source_coverage_count integer NOT NULL DEFAULT 0,
  named_decision_maker_count integer NOT NULL DEFAULT 0,
  public_contact_count integer NOT NULL DEFAULT 0,
  last_researched_at timestamp with time zone,
  brand_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  contact_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  channel_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  market_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  opportunity_hypotheses jsonb NOT NULL DEFAULT '[]'::jsonb,
  outreach_eligibility text NOT NULL DEFAULT 'hold'::text,
  outreach_eligibility_reason text,
  operational_friction_score numeric NOT NULL DEFAULT 0,
  brand_gap_score numeric NOT NULL DEFAULT 0,
  data_sufficiency_score numeric NOT NULL DEFAULT 0,
  decision_uncertainty_score numeric NOT NULL DEFAULT 100,
  traffic_relevance_score numeric NOT NULL DEFAULT 0,
  prospect_tier text NOT NULL DEFAULT 'unranked'::text,
  research_cost_tier text NOT NULL DEFAULT 'free'::text,
  research_spend_cents integer NOT NULL DEFAULT 0,
  paid_enrichment_recommended boolean NOT NULL DEFAULT false,
  paid_enrichment_reason text,
  score_version text NOT NULL DEFAULT 'legacy'::text,
  score_explanation jsonb NOT NULL DEFAULT '{}'::jsonb,
  public_phone text,
  formatted_address text,
  google_place_id text,
  google_maps_url text,
  google_rating numeric,
  google_review_count integer,
  business_status text,
  primary_business_type text,
  CONSTRAINT prospect_profiles_athrty_fit_score_check CHECK (athrty_fit_score >= 0::numeric AND athrty_fit_score <= 100::numeric),
  CONSTRAINT prospect_profiles_best_fit_check CHECK (best_fit = ANY (ARRAY['athrty'::text, 'truett-cash'::text, 'both'::text, 'low_fit'::text])),
  CONSTRAINT prospect_profiles_confidence_check CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  CONSTRAINT prospect_profiles_contactability_score_check CHECK (contactability_score >= 0::numeric AND contactability_score <= 100::numeric),
  CONSTRAINT prospect_profiles_conversion_gap_score_check CHECK (conversion_gap_score >= 0::numeric AND conversion_gap_score <= 100::numeric),
  CONSTRAINT prospect_profiles_crawl_status_check CHECK (crawl_status = ANY (ARRAY['queued'::text, 'crawling'::text, 'complete'::text, 'partial'::text, 'failed'::text, 'blocked'::text])),
  CONSTRAINT prospect_profiles_operations_complexity_score_check CHECK (operations_complexity_score >= 0::numeric AND operations_complexity_score <= 100::numeric),
  CONSTRAINT prospect_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT prospect_profiles_outreach_status_check CHECK (outreach_status = ANY (ARRAY['unreviewed'::text, 'review_ready'::text, 'approved'::text, 'nurture'::text, 'contacted'::text, 'responded'::text, 'converted'::text, 'suppressed'::text, 'disqualified'::text])),
  CONSTRAINT prospect_profiles_overall_score_check CHECK (overall_score >= 0::numeric AND overall_score <= 100::numeric),
  CONSTRAINT prospect_profiles_owner_user_id_canonical_domain_key UNIQUE (owner_user_id, canonical_domain),
  CONSTRAINT prospect_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_profiles_prospect_tier_check CHECK (prospect_tier = ANY (ARRAY['unranked'::text, 'A'::text, 'B'::text, 'C'::text, 'hold'::text])),
  CONSTRAINT prospect_profiles_research_cost_tier_check CHECK (research_cost_tier = ANY (ARRAY['free'::text, 'cheap_paid'::text, 'premium_optional'::text])),
  CONSTRAINT prospect_profiles_truett_fit_score_check CHECK (truett_fit_score >= 0::numeric AND truett_fit_score <= 100::numeric),
  CONSTRAINT prospect_profiles_website_quality_score_check CHECK (website_quality_score >= 0::numeric AND website_quality_score <= 100::numeric)
);

CREATE TABLE IF NOT EXISTS public.prospect_contact_candidates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  prospect_profile_id uuid NOT NULL,
  organization_id uuid,
  name text,
  job_title text,
  email text,
  phone text,
  contact_type text NOT NULL DEFAULT 'business'::text,
  source_url text NOT NULL,
  source_label text,
  confidence numeric NOT NULL DEFAULT 0.5,
  verification_status text NOT NULL DEFAULT 'public_site'::text,
  promoted_contact_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  seniority text,
  role_class text,
  decision_maker_score numeric NOT NULL DEFAULT 0,
  contact_quality_score numeric NOT NULL DEFAULT 0,
  source_count integer NOT NULL DEFAULT 1,
  profile_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  bio_summary text,
  last_verified_at timestamp with time zone,
  outreach_eligible boolean NOT NULL DEFAULT false,
  eligibility_reason text,
  CONSTRAINT prospect_contact_candidates_confidence_check CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  CONSTRAINT prospect_contact_candidates_contact_type_check CHECK (contact_type = ANY (ARRAY['decision_maker'::text, 'business'::text, 'department'::text, 'unknown'::text])),
  CONSTRAINT prospect_contact_candidates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT prospect_contact_candidates_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_contact_candidates_promoted_contact_id_fkey FOREIGN KEY (promoted_contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL,
  CONSTRAINT prospect_contact_candidates_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE CASCADE,
  CONSTRAINT prospect_contact_candidates_verification_status_check CHECK (verification_status = ANY (ARRAY['public_site'::text, 'verified'::text, 'unverified'::text, 'invalid'::text, 'suppressed'::text]))
);

CREATE TABLE IF NOT EXISTS public.prospect_opportunity_theses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  prospect_profile_id uuid NOT NULL,
  brand_key text NOT NULL,
  thesis_key text NOT NULL,
  title text NOT NULL,
  problem_hypothesis text NOT NULL,
  evidence_claims jsonb NOT NULL DEFAULT '[]'::jsonb,
  evidence_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  offer_match text,
  recommended_discovery_question text,
  urgency_score numeric NOT NULL DEFAULT 0,
  leverage_score numeric NOT NULL DEFAULT 0,
  confidence numeric NOT NULL DEFAULT 0,
  expected_value_low numeric,
  expected_value_high numeric,
  status text NOT NULL DEFAULT 'candidate'::text,
  disposition_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospect_opportunity_theses_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_opportunity_theses_prospect_profile_id_brand_key_t_key UNIQUE (prospect_profile_id, brand_key, thesis_key),
  CONSTRAINT prospect_opportunity_theses_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE CASCADE,
  CONSTRAINT prospect_opportunity_theses_status_check CHECK (status = ANY (ARRAY['candidate'::text, 'primary'::text, 'secondary'::text, 'validated'::text, 'invalidated'::text, 'converted'::text, 'archived'::text]))
);

CREATE TABLE IF NOT EXISTS public.prospect_account_models (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  prospect_profile_id uuid NOT NULL,
  organization_id uuid,
  lifecycle_state text NOT NULL DEFAULT 'observed'::text,
  routed_brand_key text,
  current_thesis text,
  best_channel text,
  best_channel_reason text,
  next_best_action text,
  next_best_action_reason text,
  relationship_temperature numeric NOT NULL DEFAULT 0,
  why_now_score numeric NOT NULL DEFAULT 0,
  timing_score numeric NOT NULL DEFAULT 0,
  buying_signal_score numeric NOT NULL DEFAULT 0,
  stakeholder_access_score numeric NOT NULL DEFAULT 0,
  commercial_value_score numeric NOT NULL DEFAULT 0,
  predicted_reply_probability numeric,
  predicted_meeting_probability numeric,
  predicted_win_probability numeric,
  expected_value_low numeric,
  expected_value_high numeric,
  risk_score numeric NOT NULL DEFAULT 0,
  confidence numeric NOT NULL DEFAULT 0,
  decision_state text NOT NULL DEFAULT 'observe'::text,
  decision_reason text,
  last_modeled_at timestamp with time zone,
  next_review_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  model_version text NOT NULL DEFAULT 'cashos-account-v1'::text,
  primary_thesis_id uuid,
  CONSTRAINT prospect_account_models_decision_state_check CHECK (decision_state = ANY (ARRAY['observe'::text, 'research_more'::text, 'watch'::text, 'nurture'::text, 'contact'::text, 'hold'::text, 'disqualify'::text])),
  CONSTRAINT prospect_account_models_lifecycle_state_check CHECK (lifecycle_state = ANY (ARRAY['observed'::text, 'researching'::text, 'watching'::text, 'ready'::text, 'contacted'::text, 'engaged'::text, 'qualified'::text, 'proposal'::text, 'won'::text, 'lost'::text, 'nurture'::text, 'suppressed'::text])),
  CONSTRAINT prospect_account_models_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT prospect_account_models_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_account_models_primary_thesis_id_fkey FOREIGN KEY (primary_thesis_id) REFERENCES public.prospect_opportunity_theses(id) ON DELETE SET NULL,
  CONSTRAINT prospect_account_models_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE CASCADE,
  CONSTRAINT prospect_account_models_prospect_profile_id_key UNIQUE (prospect_profile_id)
);

CREATE TABLE IF NOT EXISTS public.prospect_outreach_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  brand_key text NOT NULL,
  policy_name text NOT NULL DEFAULT 'premium_curated_v1'::text,
  active boolean NOT NULL DEFAULT true,
  min_overall_score numeric NOT NULL DEFAULT 70,
  min_brand_fit_score numeric NOT NULL DEFAULT 72,
  min_confidence numeric NOT NULL DEFAULT 0.72,
  min_evidence_quality_score numeric NOT NULL DEFAULT 70,
  min_message_quality_score numeric NOT NULL DEFAULT 80,
  min_contact_quality_score numeric NOT NULL DEFAULT 72,
  min_source_coverage integer NOT NULL DEFAULT 3,
  require_named_decision_maker boolean NOT NULL DEFAULT false,
  generic_inbox_min_overall_score numeric NOT NULL DEFAULT 88,
  generic_inbox_min_source_coverage integer NOT NULL DEFAULT 4,
  max_initial_outreach_per_day integer NOT NULL DEFAULT 8,
  max_total_outreach_per_day integer NOT NULL DEFAULT 12,
  max_active_sequences integer NOT NULL DEFAULT 40,
  max_touches_per_organization integer NOT NULL DEFAULT 3,
  min_days_between_touches integer NOT NULL DEFAULT 7,
  max_sequence_days integer NOT NULL DEFAULT 45,
  stop_on_any_reply boolean NOT NULL DEFAULT true,
  require_human_approval_initial boolean NOT NULL DEFAULT true,
  require_human_approval_followup boolean NOT NULL DEFAULT true,
  prohibit_bulk_bcc boolean NOT NULL DEFAULT true,
  prohibit_guessed_contacts boolean NOT NULL DEFAULT true,
  require_public_source_provenance boolean NOT NULL DEFAULT true,
  require_opt_out boolean NOT NULL DEFAULT true,
  require_postal_address boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospect_outreach_policies_owner_user_id_brand_key_key UNIQUE (owner_user_id, brand_key),
  CONSTRAINT prospect_outreach_policies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prospect_outreach_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  prospect_profile_id uuid NOT NULL,
  contact_candidate_id uuid,
  engagement_id uuid,
  brand_key text NOT NULL,
  sequence_key text NOT NULL DEFAULT 'initial'::text,
  sequence_step integer NOT NULL DEFAULT 1,
  channel text NOT NULL DEFAULT 'email'::text,
  state text NOT NULL DEFAULT 'draft'::text,
  evidence_url text,
  evidence_claim text,
  subject text NOT NULL,
  body text NOT NULL,
  rationale text,
  send_after timestamp with time zone,
  sent_at timestamp with time zone,
  replied_at timestamp with time zone,
  provider_message_id text,
  failure_code text,
  failure_message text,
  idempotency_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  message_quality_score numeric NOT NULL DEFAULT 0,
  specificity_score numeric NOT NULL DEFAULT 0,
  contact_quality_score numeric NOT NULL DEFAULT 0,
  evidence_quality_score numeric NOT NULL DEFAULT 0,
  policy_passed boolean NOT NULL DEFAULT false,
  policy_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  human_approved_at timestamp with time zone,
  human_approved_by uuid,
  commercial_disclosure_version text,
  opt_out_included boolean NOT NULL DEFAULT false,
  postal_address_included boolean NOT NULL DEFAULT false,
  CONSTRAINT prospect_outreach_queue_brand_key_check CHECK (brand_key = ANY (ARRAY['authority-systems'::text, 'truett-cash'::text])),
  CONSTRAINT prospect_outreach_queue_channel_check CHECK (channel = 'email'::text),
  CONSTRAINT prospect_outreach_queue_contact_candidate_id_fkey FOREIGN KEY (contact_candidate_id) REFERENCES public.prospect_contact_candidates(id) ON DELETE SET NULL,
  CONSTRAINT prospect_outreach_queue_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE SET NULL,
  CONSTRAINT prospect_outreach_queue_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_outreach_queue_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE CASCADE,
  CONSTRAINT prospect_outreach_queue_sequence_step_check CHECK (sequence_step >= 1 AND sequence_step <= 12),
  CONSTRAINT prospect_outreach_queue_state_check CHECK (state = ANY (ARRAY['draft'::text, 'review'::text, 'approved'::text, 'scheduled'::text, 'sending'::text, 'sent'::text, 'replied'::text, 'nurture'::text, 'suppressed'::text, 'failed'::text, 'cancelled'::text]))
);

CREATE TABLE IF NOT EXISTS public.prospect_response_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  prospect_profile_id uuid NOT NULL,
  outreach_queue_id uuid,
  contact_candidate_id uuid,
  provider text,
  provider_message_id text,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  subject text,
  snippet text,
  response_class text NOT NULL DEFAULT 'unclassified'::text,
  sentiment text,
  positive_intent boolean,
  opt_out boolean NOT NULL DEFAULT false,
  wrong_person boolean NOT NULL DEFAULT false,
  not_now boolean NOT NULL DEFAULT false,
  objection_key text,
  next_action text,
  confidence numeric,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospect_response_events_contact_candidate_id_fkey FOREIGN KEY (contact_candidate_id) REFERENCES public.prospect_contact_candidates(id) ON DELETE SET NULL,
  CONSTRAINT prospect_response_events_outreach_queue_id_fkey FOREIGN KEY (outreach_queue_id) REFERENCES public.prospect_outreach_queue(id) ON DELETE SET NULL,
  CONSTRAINT prospect_response_events_owner_user_id_provider_provider_me_key UNIQUE (owner_user_id, provider, provider_message_id),
  CONSTRAINT prospect_response_events_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_response_events_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE CASCADE,
  CONSTRAINT prospect_response_events_response_class_check CHECK (response_class = ANY (ARRAY['unclassified'::text, 'positive'::text, 'neutral'::text, 'not_now'::text, 'objection'::text, 'wrong_person'::text, 'negative'::text, 'opt_out'::text, 'meeting_request'::text]))
);

CREATE TABLE IF NOT EXISTS public.prospect_preview_sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prospect_profile_id uuid,
  organization_id uuid,
  slug text NOT NULL,
  industry text,
  template_family text,
  status text NOT NULL DEFAULT 'draft'::text,
  qa_score numeric(5,2),
  primary_cta text,
  offer_id text,
  checkout_url text,
  preview_url text,
  render_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  internal_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  published_at timestamp with time zone,
  sold_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospect_preview_sites_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT prospect_preview_sites_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_preview_sites_slug_key UNIQUE (slug),
  CONSTRAINT prospect_preview_sites_status_check CHECK (status = ANY (ARRAY['draft'::text, 'building'::text, 'qa'::text, 'ready'::text, 'published'::text, 'paused'::text, 'sold'::text, 'archived'::text]))
);

CREATE TABLE IF NOT EXISTS public.athrty_site_qa_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  preview_site_id uuid NOT NULL,
  run_type text NOT NULL DEFAULT 'publish_gate'::text,
  status text NOT NULL DEFAULT 'pending'::text,
  total_score numeric,
  hard_block_count integer NOT NULL DEFAULT 0,
  checks jsonb NOT NULL DEFAULT '{}'::jsonb,
  failures jsonb NOT NULL DEFAULT '[]'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  viewport_results jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  commercial_block_count integer NOT NULL DEFAULT 0,
  quality_score numeric,
  release_decision text,
  policy_version text NOT NULL DEFAULT 'athrty-qa-firewall-v1'::text,
  CONSTRAINT athrty_site_qa_runs_pkey PRIMARY KEY (id),
  CONSTRAINT athrty_site_qa_runs_preview_site_id_fkey FOREIGN KEY (preview_site_id) REFERENCES public.prospect_preview_sites(id) ON DELETE CASCADE,
  CONSTRAINT athrty_site_qa_runs_release_decision_check CHECK (release_decision IS NULL OR (release_decision = ANY (ARRAY['release'::text, 'review'::text, 'block'::text]))),
  CONSTRAINT athrty_site_qa_runs_status_check CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'passed'::text, 'failed'::text, 'blocked'::text]))
);

CREATE TABLE IF NOT EXISTS public.athrty_design_critiques (
  id uuid NOT NULL DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL, preview_site_id uuid NOT NULL, qa_run_id uuid,
  critique_stage text NOT NULL DEFAULT 'post_build'::text, critic_key text NOT NULL,
  dimension_scores jsonb NOT NULL DEFAULT '{}'::jsonb, strengths jsonb NOT NULL DEFAULT '[]'::jsonb,
  issues jsonb NOT NULL DEFAULT '[]'::jsonb, recommendations jsonb NOT NULL DEFAULT '[]'::jsonb,
  severity integer NOT NULL DEFAULT 0, verdict text NOT NULL DEFAULT 'iterate'::text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_design_critiques_pkey PRIMARY KEY (id),
  CONSTRAINT athrty_design_critiques_preview_site_id_fkey FOREIGN KEY (preview_site_id) REFERENCES public.prospect_preview_sites(id) ON DELETE CASCADE,
  CONSTRAINT athrty_design_critiques_qa_run_id_fkey FOREIGN KEY (qa_run_id) REFERENCES public.athrty_site_qa_runs(id) ON DELETE SET NULL,
  CONSTRAINT athrty_design_critiques_severity_check CHECK (severity >= 0 AND severity <= 100)
);

CREATE TABLE IF NOT EXISTS public.athrty_design_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL, skill_key text NOT NULL, name text NOT NULL,
  domain text NOT NULL, description text NOT NULL, maturity text NOT NULL DEFAULT 'candidate'::text,
  confidence numeric NOT NULL DEFAULT 0, sample_size integer NOT NULL DEFAULT 0, success_count integer NOT NULL DEFAULT 0,
  failure_count integer NOT NULL DEFAULT 0, playbook jsonb NOT NULL DEFAULT '{}'::jsonb, anti_patterns jsonb NOT NULL DEFAULT '[]'::jsonb,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb, last_learned_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_design_skills_owner_user_id_skill_key_key UNIQUE (owner_user_id, skill_key),
  CONSTRAINT athrty_design_skills_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.athrty_site_learning_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL, preview_site_id uuid, prospect_profile_id uuid,
  organization_id uuid, event_type text NOT NULL, industry text, template_family text, quality_score numeric, signal_key text,
  source_table text NOT NULL, source_row_id uuid, payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  observed_at timestamp with time zone NOT NULL DEFAULT now(), created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_site_learning_events_event_type_check CHECK (event_type = ANY (ARRAY['qa_pass'::text, 'qa_fail'::text, 'customer_change'::text, 'customer_change_pass'::text, 'customer_change_fail'::text, 'publish'::text, 'conversion'::text])),
  CONSTRAINT athrty_site_learning_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT athrty_site_learning_events_pkey PRIMARY KEY (id),
  CONSTRAINT athrty_site_learning_events_preview_site_id_fkey FOREIGN KEY (preview_site_id) REFERENCES public.prospect_preview_sites(id) ON DELETE CASCADE,
  CONSTRAINT athrty_site_learning_events_prospect_profile_id_fkey FOREIGN KEY (prospect_profile_id) REFERENCES public.prospect_profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.athrty_site_learning_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL, scope_key text NOT NULL, industry text,
  template_family text, signal_key text NOT NULL, sample_size integer NOT NULL DEFAULT 0, pass_count integer NOT NULL DEFAULT 0,
  fail_count integer NOT NULL DEFAULT 0, avg_quality_score numeric, confidence numeric NOT NULL DEFAULT 0,
  recommendation jsonb NOT NULL DEFAULT '{}'::jsonb, evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_observed_at timestamp with time zone, last_observed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_site_learning_patterns_owner_user_id_scope_key_signa_key UNIQUE (owner_user_id, scope_key, signal_key),
  CONSTRAINT athrty_site_learning_patterns_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.athrty_event_envelopes (
  id uuid NOT NULL DEFAULT gen_random_uuid(), event_name text NOT NULL, event_role text NOT NULL DEFAULT 'observed'::text,
  source_system text NOT NULL, source_event_id text NOT NULL, organization_id uuid, contact_id uuid, engagement_id uuid,
  deal_id uuid, preview_site_id uuid, session_id text, visitor_hash text, channel text, touchpoint text, action text,
  section text, component text, destination text, attribution jsonb NOT NULL DEFAULT '{}'::jsonb,
  context jsonb NOT NULL DEFAULT '{}'::jsonb, policy_version text NOT NULL DEFAULT 'athrty-event-contract-v1'::text,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(), created_at timestamp with time zone NOT NULL DEFAULT now(),
  idempotency_key text NOT NULL,
  CONSTRAINT athrty_event_envelopes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL,
  CONSTRAINT athrty_event_envelopes_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE SET NULL,
  CONSTRAINT athrty_event_envelopes_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE SET NULL,
  CONSTRAINT athrty_event_envelopes_event_role_check CHECK (event_role = ANY (ARRAY['observed'::text, 'operational'::text, 'commerce'::text, 'derived'::text])),
  CONSTRAINT athrty_event_envelopes_idempotency_key_key UNIQUE (idempotency_key),
  CONSTRAINT athrty_event_envelopes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL,
  CONSTRAINT athrty_event_envelopes_pkey PRIMARY KEY (id),
  CONSTRAINT athrty_event_envelopes_preview_site_id_fkey FOREIGN KEY (preview_site_id) REFERENCES public.prospect_preview_sites(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.athrty_lifecycle_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(), entity_type text NOT NULL, entity_id uuid NOT NULL, from_state text,
  to_state text NOT NULL, trigger_key text NOT NULL, actor_type text NOT NULL, actor_id text,
  source text NOT NULL DEFAULT 'athrty_orchestrator'::text, source_event_id uuid, idempotency_key text NOT NULL,
  policy_version text NOT NULL, input_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb, side_effects jsonb NOT NULL DEFAULT '[]'::jsonb,
  approval_context jsonb, created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_lifecycle_events_idempotency_key_key UNIQUE (idempotency_key),
  CONSTRAINT athrty_lifecycle_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.athrty_lifecycle_state (
  entity_type text NOT NULL, entity_id uuid NOT NULL, lifecycle_state text NOT NULL, policy_version text NOT NULL,
  source_event_id uuid, last_transition_id uuid, state_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(), created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_lifecycle_state_pkey PRIMARY KEY (entity_type, entity_id)
);

CREATE TABLE IF NOT EXISTS public.athrty_transition_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(), policy_version text NOT NULL, entity_type text NOT NULL, from_state text NOT NULL,
  to_state text NOT NULL, trigger_key text NOT NULL, allowed_actor_types text[] NOT NULL DEFAULT ARRAY['system'::text],
  required_data_keys text[] NOT NULL DEFAULT '{}'::text[], side_effects jsonb NOT NULL DEFAULT '[]'::jsonb,
  requires_human_approval boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT athrty_transition_policies_pkey PRIMARY KEY (id),
  CONSTRAINT athrty_transition_policies_policy_version_entity_type_from__key UNIQUE (policy_version, entity_type, from_state, to_state, trigger_key)
);
