import { createClient } from "npm:@supabase/supabase-js@2.57.4";
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(code:string,status=400,detail?:unknown){return json({ok:false,error:{code,detail:detail??null}},status)}
function txt(v:unknown){return typeof v==="string"?v.trim():""}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0}
function clamp(v:number,min=0,max=100){return Math.max(min,Math.min(max,Number.isFinite(v)?v:0))}
function arr(v:any){return Array.isArray(v)?v:[]}
function roleMap(c:any,brand:string){const r=String(c?.role_class||""),t=String(c?.contact_type||"");let buying="unknown",influence=35;if(r==="owner"||r==="founder"){buying="economic_buyer";influence=100}else if(r==="executive"){buying="decision_maker";influence=94}else if(r==="operations_leader"){buying=brand==="authority-systems"?"decision_maker":"influencer";influence=88}else if(r==="marketing_leader"){buying=brand==="truett-cash"?"decision_maker":"influencer";influence=88}else if(r==="sales_leader"){buying="influencer";influence=80}else if(t==="decision_maker"){buying="decision_maker";influence=82}else if(t==="department"){buying="gatekeeper";influence=42}else if(t==="business"){buying="influencer";influence=55}const access=clamp(num(c?.contact_quality_score)*0.62+num(c?.confidence)*100*0.18+(c?.outreach_eligible?20:0));return {buying,influence,access}}
function triggerSpec(key:string,title:string,strength:number,a:number,t:number,summary:string){return {key,title,strength,a,t,summary}}
Deno.serve(async req=>{
 if(req.method!=="POST")return fail("METHOD_NOT_ALLOWED",405);const auth=req.headers.get("authorization")||"";if(!auth.toLowerCase().startsWith("bearer "))return fail("AUTH_REQUIRED",401);
 const su=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!su||!anon||!service)return fail("SERVER_CONFIG_ERROR",500);
 const ac=createClient(su,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const ur=await ac.auth.getUser();if(ur.error||!ur.data.user?.id)return fail("AUTH_INVALID",401);const owner=ur.data.user.id,db=createClient(su,service,{auth:{persistSession:false}});
 let b:any;try{b=await req.json()}catch{return fail("INVALID_JSON")};const profileId=txt(b?.prospect_profile_id);if(!profileId)return fail("PROSPECT_PROFILE_ID_REQUIRED");
 try{
  const pr=await db.from("prospect_profiles").select("*,organizations(id,name)").eq("id",profileId).eq("owner_user_id",owner).maybeSingle();if(pr.error||!pr.data)return fail("PROFILE_NOT_FOUND",404,pr.error?.message);const p:any=pr.data;
  const brand=p.best_fit==="truett-cash"?"truett-cash":(num(p.truett_fit_score)>num(p.athrty_fit_score)?"truett-cash":"authority-systems");const fit=num(brand==="truett-cash"?p.truett_fit_score:p.athrty_fit_score);
  const [contactsR,brandR,evidenceR,triggersR,outreachR,dealsR,engR,playsR]=await Promise.all([
    db.from("prospect_contact_candidates").select("*").eq("prospect_profile_id",profileId).order("contact_quality_score",{ascending:false}),
    db.from("prospect_brand_profiles").select("*").eq("prospect_profile_id",profileId).maybeSingle(),
    db.from("prospect_evidence").select("id,url,title,snippet,observed_at").eq("prospect_profile_id",profileId).order("observed_at",{ascending:false}).limit(12),
    db.from("prospect_buying_triggers").select("*").eq("prospect_profile_id",profileId).eq("status","active").order("observed_at",{ascending:false}),
    db.from("prospect_outreach_queue").select("id,state,sent_at,replied_at,brand_key,contact_candidate_id,evidence_claim,metadata").eq("prospect_profile_id",profileId).order("created_at",{ascending:false}).limit(20),
    p.organization_id?db.from("deals").select("*").eq("organization_id",p.organization_id).order("created_at",{ascending:false}).limit(10):Promise.resolve({data:[]}),
    db.from("engagements").select("id,pipeline_stage,status,booking_confirmed,booking_confirmed_at,next_action,metadata").eq("metadata->>prospect_profile_id",profileId).order("created_at",{ascending:false}).limit(10),
    db.from("acquisition_playbooks").select("*").eq("owner_user_id",owner).eq("brand_key",brand).in("status",["preferred","validated"]).order("confidence",{ascending:false}).limit(5)
  ]);
  const contacts:any[]=contactsR.data||[],bp:any=brandR.data||{},evidence:any[]=evidenceR.data||[],outreach:any[]=outreachR.data||[],deals:any[]=dealsR.data||[],eng:any[]=engR.data||[],plays:any[]=playsR.data||[];
  let maxAccess=0;for(let i=0;i<contacts.length;i++){const c=contacts[i],m=roleMap(c,brand);maxAccess=Math.max(maxAccess,m.access);const ex=await db.from("prospect_stakeholder_graph").select("id").eq("prospect_profile_id",profileId).eq("contact_candidate_id",c.id).maybeSingle();const row={owner_user_id:owner,prospect_profile_id:profileId,contact_candidate_id:c.id,stakeholder_name:c.name||null,stakeholder_role:c.job_title||c.role_class||null,buying_role:m.buying,influence_score:m.influence,access_score:m.access,relationship_state:outreach.some(o=>o.contact_candidate_id===c.id&&o.replied_at)?"engaged":outreach.some(o=>o.contact_candidate_id===c.id&&o.sent_at)?"contacted":"uncontacted",priority_rank:i+1,evidence:[{source_url:c.source_url,verification_status:c.verification_status,role_class:c.role_class}],confidence:num(c.confidence),last_verified_at:c.last_verified_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(ex.data?.id)await db.from("prospect_stakeholder_graph").update(row).eq("id",ex.data.id);else await db.from("prospect_stakeholder_graph").insert(row)}
  const s:any=p.signals||{};const specs:any[]=[];if(s.has_quote_or_estimate_cta)specs.push(triggerSpec("structural:quote_estimate_flow","Visible quote / estimate intake",42,62,35,"The public site exposes a quote or estimate path; this is a structural workflow surface, not proof of internal friction."));if(s.has_booking)specs.push(triggerSpec("structural:booking_flow","Visible booking flow",38,54,42,"The public site exposes appointment or booking behavior; downstream coordination may be worth understanding."));if(num(p.operational_friction_score)>=70)specs.push(triggerSpec("structural:operational_friction","High modeled operational friction",48,78,24,"Multiple public operating clues combine into a high structural-friction score; treat as a hypothesis to validate."));if(num(p.brand_gap_score)>=70)specs.push(triggerSpec("structural:brand_gap","High modeled brand / conversion gap",46,22,82,"Public brand, proof, or conversion evidence indicates a material presentation gap; treat as a hypothesis to validate."));if(maxAccess>=72)specs.push(triggerSpec("access:decision_maker","Strong public stakeholder access",34,48,48,"A high-quality publicly sourced contact is available, reducing access friction."));if(num(p.google_review_count)>=25)specs.push(triggerSpec("market:established_reputation","Established public reputation footprint",32,36,48,"Review volume suggests meaningful market activity, but does not by itself indicate purchase intent."));
  for(const x of specs){const ex=await db.from("prospect_buying_triggers").select("id").eq("owner_user_id",owner).eq("prospect_profile_id",profileId).eq("trigger_key",x.key).eq("status","active").maybeSingle();if(!ex.data?.id)await db.from("prospect_buying_triggers").insert({owner_user_id:owner,prospect_profile_id:profileId,trigger_type:"structural_signal",trigger_key:x.key,title:x.title,summary:x.summary,source_type:"cashos_model",source_url:p.website,evidence:{score_version:p.score_version,public_evidence_only:true},strength_score:x.strength,athrty_relevance_score:x.a,truett_relevance_score:x.t,confidence:Math.max(0.55,num(p.confidence)),status:"active"})}
  const active=await db.from("prospect_buying_triggers").select("*").eq("prospect_profile_id",profileId).eq("status","active");const ts:any[]=active.data||[];let why=0;if(ts.length){const weights=ts.map(x=>num(x.strength_score)*(num(brand==="truett-cash"?x.truett_relevance_score:x.athrty_relevance_score)/100)*Math.max(.4,num(x.confidence)));why=clamp(weights.reduce((a,c)=>a+c,0)/Math.max(1,Math.sqrt(weights.length)))}
  const evidenceUrls=evidence.map(x=>x.url).filter(Boolean).slice(0,4);const opportunityList=arr(brand==="truett-cash"?bp.truett_opportunities:bp.athrty_opportunities);const thesisText=txt(opportunityList[0])||txt(p.recommended_angle)||(brand==="authority-systems"?"There may be leverage in simplifying a visible workflow, handoff, or ownership boundary.":"There may be leverage in improving how the business presents proof and converts attention into a clear next step.");const thesisKey=brand==="authority-systems"?"workflow-leverage":"brand-conversion-leverage";const q=brand==="authority-systems"?"What part of that workflow still depends most on manual handoffs, re-entry, or somebody remembering the next step?":"What part of the current site or brand experience most undersells the quality of the business?";
  const th=await db.from("prospect_opportunity_theses").upsert({owner_user_id:owner,prospect_profile_id:profileId,brand_key:brand,thesis_key:thesisKey,title:brand==="authority-systems"?"Workflow leverage hypothesis":"Brand / conversion leverage hypothesis",problem_hypothesis:thesisText,evidence_claims:[p.recommended_angle,p.summary].filter(Boolean),evidence_urls:evidenceUrls,offer_match:p.recommended_offer||null,recommended_discovery_question:q,urgency_score:why,leverage_score:fit,confidence:Math.min(1,Math.max(.45,num(p.confidence))),status:"primary",updated_at:new Date().toISOString()},{onConflict:"prospect_profile_id,brand_key,thesis_key"}).select("*").single();if(th.error)throw th.error;
  const won=deals.some(d=>String(d.stage||"").toLowerCase()==="won"||d.won_at),lost=deals.some(d=>String(d.stage||"").toLowerCase()==="lost"||d.lost_at),booked=eng.some(e=>e.booking_confirmed),replied=outreach.some(o=>o.replied_at||o.state==="replied"),sent=outreach.some(o=>o.sent_at||o.state==="sent");let lifecycle="observed";if(p.suppress_outreach)lifecycle="suppressed";else if(won)lifecycle="won";else if(lost)lifecycle="lost";else if(deals.some(d=>String(d.stage||"").toLowerCase().includes("proposal")))lifecycle="proposal";else if(booked)lifecycle="qualified";else if(replied)lifecycle="engaged";else if(sent)lifecycle="contacted";else if(p.prospect_tier==="A"||p.prospect_tier==="B")lifecycle="ready";else lifecycle="observed";
  const bestContact=contacts.find(c=>c.outreach_eligible&&["public_site","verified"].includes(c.verification_status))||contacts[0]||null;let bestChannel="research",channelReason="No sufficiently verified contact channel is available.";if(bestContact?.email&&bestContact?.outreach_eligible){bestChannel="email";channelReason="Highest-quality public decision-maker/contact path is email."}else if(p.public_phone){bestChannel="phone_review";channelReason="A public company phone is available, but calling remains a human-reviewed action."}
  const tier=String(p.prospect_tier||"hold").toUpperCase();let decision="observe",reason="Continue observation until fit and evidence justify action.";
  if(p.suppress_outreach){decision="disqualify";reason="Outreach suppression is active."}
  else if(p.paid_enrichment_recommended){decision="research_more";reason="Current model says one bounded enrichment step could materially change the decision."}
  else if((tier==="A"||tier==="B")&&num(p.data_sufficiency_score)>=76&&maxAccess>=55){const evidenceStrong=num(p.evidence_quality_score)>=82;const priorityStrong=num(p.commercial_priority_score)>=60;if(why>=28||(evidenceStrong&&priorityStrong)||(tier==="A"&&num(p.overall_score)>=70)){decision="contact";reason=why>=28?"Strong fit, sufficient evidence, stakeholder access, and a credible why-now signal.":"High-confidence evergreen fit with strong public evidence, access, and commercial priority.";}else{decision="watch";reason="Strong account fit, but timing evidence is not yet strong enough for premium outbound."}}
  else if(tier==="C"){decision="nurture";reason="Plausible fit, but not enough commercial priority for active outreach."}
  else if(tier==="HOLD"){decision="hold";reason="Current evidence does not justify commercial attention."}
  const play=plays[0]||null;if(play?.recommended_channel&&decision==="contact"){bestChannel=play.recommended_channel;channelReason=`Validated playbook ${play.title} currently favors this channel.`}
  const valueScore=clamp(fit*.42+num(p.overall_score)*.22+why*.18+maxAccess*.10+num(p.evidence_quality_score)*.08);const model=await db.from("prospect_account_models").upsert({owner_user_id:owner,prospect_profile_id:profileId,organization_id:p.organization_id,routed_brand_key:brand,current_thesis:thesisText,primary_thesis_id:th.data.id,best_channel:bestChannel,best_channel_reason:channelReason,next_best_action:decision,next_best_action_reason:reason,relationship_temperature:replied?75:sent?40:0,why_now_score:why,timing_score:why,buying_signal_score:why,stakeholder_access_score:maxAccess,commercial_value_score:valueScore,risk_score:clamp(100-num(p.data_sufficiency_score)),confidence:num(p.confidence),decision_state:decision,decision_reason:reason,lifecycle_state:lifecycle,last_modeled_at:new Date().toISOString(),next_review_at:["watch","nurture","observe"].includes(decision)?new Date(Date.now()+(tier==="A"?14:tier==="B"?30:45)*86400000).toISOString():null,model_version:"cashos-account-v1",metadata:{tier,fit_score:fit,overall_score:p.overall_score,data_sufficiency_score:p.data_sufficiency_score,active_trigger_count:ts.length,best_contact_id:bestContact?.id||null,playbook_id:play?.id||null,calibration:"local_service_v2_1"},updated_at:new Date().toISOString()},{onConflict:"prospect_profile_id"}).select("*").single();if(model.error)throw model.error;
  await db.from("prospect_watch_state").upsert({owner_user_id:owner,prospect_profile_id:profileId,watch_enabled:["watch","nurture","observe"].includes(decision),watch_reason:reason,watch_frequency_days:tier==="A"?14:tier==="B"?30:45,next_check_at:["watch","nurture","observe"].includes(decision)?model.data.next_review_at:null,updated_at:new Date().toISOString()},{onConflict:"prospect_profile_id"});
  const brandRow=await db.from("brands").select("id").eq("owner_user_id",owner).eq("key",brand).maybeSingle();for(const key of ["stakeholder-mapper","buying-trigger-analyst","account-intelligence-architect","commercial-strategist"]){const ad=await db.from("agent_definitions").select("id").eq("owner_user_id",owner).eq("agent_key",key).maybeSingle();if(ad.data?.id)await db.from("agent_runs").upsert({owner_user_id:owner,agent_definition_id:ad.data.id,brand_id:brandRow.data?.id||null,trigger_type:"account_refresh",source_type:"prospect_profile",source_id:profileId,objective:`${key} refreshed account intelligence`,status:"succeeded",priority:Math.round(valueScore),idempotency_key:`ssplus:${profileId}:${key}:${new Date().toISOString().slice(0,10)}`,context:{prospect_profile_id:profileId},output:{decision_state:decision,why_now_score:why,stakeholder_access_score:maxAccess,commercial_value_score:valueScore},started_at:new Date().toISOString(),completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"owner_user_id,idempotency_key"})}
  return json({ok:true,account_model:model.data,primary_thesis:th.data,stakeholders:contacts.length,active_triggers:ts.length,decision:{state:decision,reason,best_channel:bestChannel},watch:["watch","nurture","observe"].includes(decision)});
 }catch(e:any){return fail("ACCOUNT_INTELLIGENCE_FAILED",500,String(e?.message||e).slice(0,1600))}
});