import { createClient } from "npm:@supabase/supabase-js@2.57.4";
type Action="get_learning_summary"|"get_decision_queue"|"get_agent_state"|"get_execution_queue";
const ACTIONS=new Set<Action>(["get_learning_summary","get_decision_queue","get_agent_state","get_execution_queue"]);
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(c:string,s=400,d?:unknown){return json({ok:false,error:{code:c,detail:d??null}},s)}
function txt(v:unknown){return typeof v==="string"?v.trim():""}
async function sha256(s:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function actor(req:Request,url:string,anon:string,service:string){const db=createClient(url,service,{auth:{persistSession:false}});const key=txt(req.headers.get("x-cash-agent-key"));if(key){const h=await sha256(key);const q=await db.from("agent_service_keys").select("id,owner_user_id,scopes,status,expires_at").eq("key_hash",h).eq("status","active").maybeSingle();if(q.error||!q.data)return null;if(q.data.expires_at&&new Date(q.data.expires_at).getTime()<=Date.now())return null;const scopes=Array.isArray(q.data.scopes)?q.data.scopes.map(String):[];if(!scopes.includes("operating_feed:read"))return null;await db.from("agent_service_keys").update({last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",q.data.id);return{owner:String(q.data.owner_user_id),mode:"service",db}}const auth=req.headers.get("authorization");if(!auth?.toLowerCase().startsWith("bearer "))return null;const ac=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const u=await ac.auth.getUser();if(u.error||!u.data?.user?.id)return null;return{owner:u.data.user.id,mode:"user",db}}
Deno.serve(async req=>{if(req.method!=="POST")return fail("METHOD_NOT_ALLOWED",405);const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!anon||!service)return fail("SERVER_CONFIG_ERROR",500);let b:any;try{b=await req.json()}catch{return fail("INVALID_JSON")};const action=b?.action as Action;if(!ACTIONS.has(action))return fail("INVALID_ACTION");const a=await actor(req,url,anon,service);if(!a)return fail("AUTH_INVALID",401);const {owner,db}=a;try{
 if(action==="get_learning_summary"){let q=db.from("learning_opportunities").select("id,brand_id,opportunity_key,taxonomy_key,title,summary,status,opportunity_score,confidence,conversation_count,organization_count,booked_count,conversion_rate,recommended_action,recommended_agent_key,evidence_conversation_ids,decision_execution_count,successful_decision_count,failed_decision_count,avg_decision_success_score,last_decision_outcome_at,last_observed_at,updated_at").eq("owner_user_id",owner).in("status",["active","watch"]).order("opportunity_score",{ascending:false}).limit(Math.min(50,Math.max(1,Number(b?.limit)||20)));if(b?.brand_id)q=q.eq("brand_id",txt(b.brand_id));const o=await q;if(o.error)throw o.error;const c=await db.from("learning_cycles").select("id,brand_id,trigger_type,status,window_start,window_end,conversations_scanned,signals_normalized,rollups_written,opportunities_written,decisions_written,summary,completed_at,created_at").eq("owner_user_id",owner).order("created_at",{ascending:false}).limit(5);if(c.error)throw c.error;return json({ok:true,action,actor_mode:a.mode,data:{opportunities:o.data??[],recent_cycles:c.data??[]}})}
 if(action==="get_decision_queue"){let q=db.from("decision_paths").select("id,brand_id,decision_type,title,summary,decision_source,status,confidence,priority,source_ref,metadata,effective_from,updated_at").eq("owner_user_id",owner).eq("status","proposed").order("priority",{ascending:false}).order("updated_at",{ascending:false}).limit(Math.min(50,Math.max(1,Number(b?.limit)||20)));if(b?.brand_id)q=q.eq("brand_id",txt(b.brand_id));const d=await q;if(d.error)throw d.error;const ids=(d.data??[]).map((x:any)=>x.id);let evidence:any[]=[];if(ids.length){const e=await db.from("decision_evidence").select("decision_id,role,weight,evidence_ref_id,intelligence_evidence_refs(id,evidence_kind,canonical_table,canonical_row_uuid,observed_at,evidence_summary)").eq("owner_user_id",owner).in("decision_id",ids);if(e.error)throw e.error;evidence=e.data??[]}return json({ok:true,action,actor_mode:a.mode,data:{decisions:d.data??[],evidence}})}
 if(action==="get_agent_state"){const agents=await db.from("agent_definitions").select("id,agent_key,name,agent_class,execution_mode,brand_id,status,objective,capabilities,tool_allowlist,approval_policy,runtime_ref").eq("owner_user_id",owner).order("agent_class").order("agent_key");if(agents.error)throw agents.error;let r=db.from("agent_runs").select("id,agent_definition_id,brand_id,parent_run_id,trigger_type,source_type,source_id,objective,status,priority,context,output,error_code,error_message,started_at,completed_at,created_at,updated_at,agent_definitions(agent_key,name,agent_class)").eq("owner_user_id",owner).in("status",["queued","running","waiting_review","blocked"]).order("priority",{ascending:false}).order("created_at",{ascending:false}).limit(50);if(b?.brand_id)r=r.eq("brand_id",txt(b.brand_id));const rr=await r;if(rr.error)throw rr.error;return json({ok:true,action,actor_mode:a.mode,data:{agents:agents.data??[],active_runs:rr.data??[]}})}
 if(action==="get_execution_queue"){let q=db.from("decision_executions").select("id,brand_id,decision_id,opportunity_id,parent_execution_id,attempt_no,execution_lineage_key,worker_agent_key,jarvis_job_id,live_action_lineage_key,status,approval_source,execution_plan,result,error_code,error_message,accepted_at,delegated_at,started_at,completed_at,updated_at,decision_paths(id,title,summary,status,priority,metadata),learning_opportunities(id,title,taxonomy_key,opportunity_score,confidence)").eq("owner_user_id",owner).in("status",["accepted","queued","delegated","running","waiting_review"]).order("updated_at",{ascending:false}).limit(Math.min(50,Math.max(1,Number(b?.limit)||20)));if(b?.brand_id)q=q.eq("brand_id",txt(b.brand_id));const x=await q;if(x.error)throw x.error;return json({ok:true,action,actor_mode:a.mode,data:{executions:x.data??[]}})}
 return fail("INVALID_ACTION")
 }catch(e:any){return fail("JARVIS_FEED_FAILED",500,String(e?.message??e).slice(0,1500))}});