import Stripe from 'npm:stripe@^22'
import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
type StripeWebhookEvent={id:string,type:string,api_version?:string,livemode?:boolean,data?:any}
const GRAPH='https://graph.microsoft.com/v1.0';const SENDER='hello@athrty.co';
function jsonResponse(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8'}})}
function pickServiceRoleKey(){const direct=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')?.trim();if(direct)return direct;const raw=Deno.env.get('SUPABASE_SECRET_KEYS');if(!raw)throw new Error('SUPABASE service role is required');const keys:Record<string,string>=JSON.parse(raw);const hit=Object.entries(keys).find(([k])=>/service_role/i.test(k));const key=hit?hit[1]:keys.default||Object.values(keys)[0];if(!key)throw new Error('No Supabase secret keys available');return key}
async function callProcessStripeEvent(event:StripeWebhookEvent){const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SUPABASE_URL is required');const key=pickServiceRoleKey();const r=await fetch(`${url}/rest/v1/rpc/process_stripe_event`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`,apikey:key},body:JSON.stringify({event})});const t=await r.text();if(!r.ok)throw new Error(`process_stripe_event RPC returned ${r.status}: ${t.slice(0,300)}`);try{return t?JSON.parse(t):null}catch{return t.slice(0,200)}}
async function graphToken(){const tenant=Deno.env.get('M365_TENANT_ID')?.trim(),client=Deno.env.get('M365_CLIENT_ID')?.trim(),secret=Deno.env.get('M365_CLIENT_SECRET')?.trim();if(!tenant||!client||!secret)throw new Error('M365_CONFIG_MISSING');const r=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client,client_secret:secret,grant_type:'client_credentials',scope:'https://graph.microsoft.com/.default'})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.access_token)throw new Error('M365_AUTH_FAILED');return j.access_token as string}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[c]||c))}
async function sendOnboarding(event:StripeWebhookEvent){if(event.type!=='checkout.session.completed')return;const s:any=event.data?.object||{};if(String(s.payment_status||'')!=='paid')return;const md:any=s.metadata||{};const email=String(s.customer_details?.email||s.customer_email||'').trim().toLowerCase();if(!email||!email.includes('@'))return;if(!md.preview_slug&&!md.preview_id&&!md.build_id)return;const company=String(md.company||md.organization_name||'your business').trim();const offer=String(md.offer_id||'website launch').trim();const token=await graphToken();const html=`<div style="font-family:Arial,sans-serif;color:#111;line-height:1.6;max-width:560px"><h1 style="font-size:24px;margin:0 0 18px">You bought the site. Here is what happens next.</h1><p>We already have the website build.</p><p><strong>1. Reply to this email with your domain name.</strong><br>Example: yourbusiness.com</p><p><strong>2. Tell us where the domain is managed.</strong><br>GoDaddy, Squarespace, Namecheap, Cloudflare, or whoever you use.</p><p><strong>3. We connect it and turn the site live.</strong></p><p>That is it. No technical setup on your side unless the domain company asks you to approve something.</p><p style="margin-top:24px"><strong>Order:</strong> ${esc(offer)}${company?`<br><strong>Business:</strong> ${esc(company)}`:''}</p><p style="margin-top:26px">Reply here if you get stuck. We will tell you exactly what to click.</p><p style="margin-top:28px;font-size:12px;color:#666">ATHRTY Systems | hello@athrty.co</p></div>`;const r=await fetch(`${GRAPH}/users/${encodeURIComponent(SENDER)}/sendMail`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({message:{subject:'Your website is ready to connect',body:{contentType:'HTML',content:html},toRecipients:[{emailAddress:{address:email}}],replyTo:[{emailAddress:{address:SENDER}}]},saveToSentItems:true})});if(!r.ok)throw new Error(`ONBOARDING_EMAIL_FAILED_${r.status}`)}
async function reconcilePreviewSale(event:StripeWebhookEvent){if(event.type!=='checkout.session.completed')return;const s:any=event.data?.object||{};if(String(s.payment_status||'')!=='paid')return;const md:any=s.metadata||{};const previewId=String(md.preview_id||'').trim(),profileId=String(md.prospect_profile_id||'').trim();if(!previewId&&!profileId)return;const su=Deno.env.get('SUPABASE_URL')?.trim();if(!su)return;const db=createClient(su,pickServiceRoleKey(),{auth:{persistSession:false}});const now=new Date().toISOString();if(previewId){await db.from('prospect_preview_sites').update({status:'sold',sold_at:now,updated_at:now,internal_metadata:{purchase:{stripe_session_id:s.id,order_id:md.order_id||null,offer_id:md.offer_id||null,paid_at:now}}}).eq('id',previewId)}if(profileId){await db.from('prospect_profiles').update({outreach_status:'converted',updated_at:now}).eq('id',profileId);await db.from('prospect_outreach_queue').update({state:'cancelled',updated_at:now,metadata:{conversion_stop:true,conversion_source:'stripe_preview_checkout',stripe_session_id:s.id}}).eq('prospect_profile_id',profileId).in('state',['draft','review','approved','scheduled','nurture'])}}
const cryptoProvider=Stripe.createSubtleCryptoProvider();const stripe=new Stripe('sk_dummy',{apiVersion:'2024-06-20',typescript:true});
function getWebhookSecret(){const s=Deno.env.get('STRIPE_WEBHOOK_SECRET');if(!s)throw new Error('STRIPE_WEBHOOK_SECRET is required');return s.trim()}
function classify(m:string){if(m.includes('No signatures found matching'))return'SIGNATURE_MISMATCH';if(m.includes('No stripe-signature')||m.includes('Missing Stripe-Signature'))return'MISSING_SIGNATURE';if(m.includes('Timestamp outside'))return'TIMESTAMP_TOLERANCE';return'OTHER_SIGNATURE_ERROR'}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return jsonResponse({error:'METHOD_NOT_ALLOWED'},405);const sig=req.headers.get('Stripe-Signature'),body=await req.text();let event:StripeWebhookEvent;try{event=await stripe.webhooks.constructEventAsync(body,sig!,getWebhookSecret(),undefined,cryptoProvider) as StripeWebhookEvent}catch(error){console.warn('stripe webhook signature verification failed',{reason:classify(error instanceof Error?error.message:String(error))});return jsonResponse({error:'INVALID_SIGNATURE'},400)}if(!event||typeof event.id!=='string'||typeof event.type!=='string')return jsonResponse({error:'INVALID_STRIPE_EVENT'},400);try{await callProcessStripeEvent(event)}catch(error){console.error('stripe event processing failed',{event_id:event.id,message:error instanceof Error?error.message:'unknown'});return jsonResponse({error:'PROCESSING_FAILED'},500)}try{await reconcilePreviewSale(event)}catch(error){console.error('preview sale reconciliation failed',{event_id:event.id,message:error instanceof Error?error.message:'unknown'})}try{await sendOnboarding(event)}catch(error){console.error('post purchase onboarding failed',{event_id:event.id,message:error instanceof Error?error.message:'unknown'})}return jsonResponse({received:true},200)})