-- ATHRTY Outbound Sequence + Compliance Guard v1
-- 1) Prevent duplicate/restarted initial-touch sequences for prospects that already have
--    an active initial touch or a historical sent/replied touch.
-- 2) Normalize the delivery adapter's guaranteed commercial footer package before the
--    existing outreach policy guard evaluates a red-team/quality-reviewed draft.

CREATE OR REPLACE FUNCTION private.athrty_normalize_delivery_compliance_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
BEGIN
  IF NEW.channel = 'email'
     AND COALESCE((NEW.metadata ->> 'ss_plus_red_team_passed')::boolean, false) IS TRUE
     AND COALESCE(NEW.message_quality_score, 0) > 0
     AND COALESCE(NEW.specificity_score, 0) > 0 THEN
    NEW.opt_out_included := true;
    NEW.postal_address_included := true;
    NEW.commercial_disclosure_version := 'can_spam_footer_v4_ascii';
    NEW.metadata := COALESCE(NEW.metadata, '{}'::jsonb) || jsonb_build_object(
      'delivery_compliance_mode', 'server_injected_footer',
      'delivery_compliance_version', 'can_spam_footer_v4_ascii'
    );
  END IF;
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS a_athrty_delivery_compliance_v1_trg ON public.prospect_outreach_queue;
CREATE TRIGGER a_athrty_delivery_compliance_v1_trg
BEFORE INSERT OR UPDATE OF channel, metadata, message_quality_score, specificity_score
ON public.prospect_outreach_queue
FOR EACH ROW
EXECUTE FUNCTION private.athrty_normalize_delivery_compliance_v1();

CREATE OR REPLACE FUNCTION private.athrty_guard_initial_sequence_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
BEGIN
  IF COALESCE(NEW.sequence_step, 1) = 1
     AND NEW.state IN ('draft','review','approved','scheduled','sending') THEN

    IF TG_OP = 'UPDATE'
       AND OLD.state IN ('sent','replied') THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'ATHRTY_INITIAL_TOUCH_IMMUTABLE_AFTER_DELIVERY';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM public.prospect_outreach_queue q
      WHERE q.owner_user_id = NEW.owner_user_id
        AND q.prospect_profile_id = NEW.prospect_profile_id
        AND q.id IS DISTINCT FROM NEW.id
        AND q.state IN ('sent','replied')
    ) THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'ATHRTY_PRIOR_TOUCH_REQUIRES_FOLLOWUP_SEQUENCE';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM public.prospect_outreach_queue q
      WHERE q.owner_user_id = NEW.owner_user_id
        AND q.prospect_profile_id = NEW.prospect_profile_id
        AND q.id IS DISTINCT FROM NEW.id
        AND COALESCE(q.sequence_step, 1) = 1
        AND q.state IN ('draft','review','approved','scheduled','sending')
    ) THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'ATHRTY_ACTIVE_INITIAL_TOUCH_ALREADY_EXISTS';
    END IF;
  END IF;

  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS aa_athrty_initial_sequence_guard_v1_trg ON public.prospect_outreach_queue;
CREATE TRIGGER aa_athrty_initial_sequence_guard_v1_trg
BEFORE INSERT OR UPDATE OF state, sequence_step, prospect_profile_id, owner_user_id
ON public.prospect_outreach_queue
FOR EACH ROW
EXECUTE FUNCTION private.athrty_guard_initial_sequence_v1();

-- Clean only the active v4 initial drafts generated by the refresh bug when a historical
-- delivered touch already exists for the same prospect. Historical sent rows are untouched.
UPDATE public.prospect_outreach_queue q
SET state = 'cancelled',
    failure_code = 'DUPLICATE_INITIAL_SEQUENCE_BLOCKED',
    failure_message = 'Cancelled by outbound sequence integrity guard; prior delivered touch requires follow-up sequence.',
    metadata = COALESCE(q.metadata, '{}'::jsonb) || jsonb_build_object(
      'sequence_guard_cleanup_version', 'athrty_sequence_guard_v1',
      'sequence_guard_cleanup_at', now()
    ),
    updated_at = now()
WHERE q.sequence_key = 'athrty-trust-v4'
  AND COALESCE(q.sequence_step, 1) = 1
  AND q.state IN ('draft','review','approved','scheduled')
  AND EXISTS (
    SELECT 1
    FROM public.prospect_outreach_queue h
    WHERE h.owner_user_id = q.owner_user_id
      AND h.prospect_profile_id = q.prospect_profile_id
      AND h.id <> q.id
      AND h.state IN ('sent','replied')
  );

-- Backfill the guaranteed server-side compliance package for current legitimate active
-- drafts that already completed red-team + quality scoring. The existing policy trigger
-- recomputes policy_passed on this UPDATE; this does not approve or send any row.
UPDATE public.prospect_outreach_queue q
SET opt_out_included = true,
    postal_address_included = true,
    commercial_disclosure_version = 'can_spam_footer_v4_ascii',
    metadata = COALESCE(q.metadata, '{}'::jsonb) || jsonb_build_object(
      'delivery_compliance_mode', 'server_injected_footer',
      'delivery_compliance_version', 'can_spam_footer_v4_ascii',
      'delivery_compliance_backfill_at', now()
    ),
    updated_at = now()
WHERE q.channel = 'email'
  AND q.state IN ('draft','review')
  AND COALESCE((q.metadata ->> 'ss_plus_red_team_passed')::boolean, false) IS TRUE
  AND COALESCE(q.message_quality_score, 0) > 0
  AND COALESCE(q.specificity_score, 0) > 0;
