import { IntegrationProvider } from './types';

export const providers: IntegrationProvider[] = [
  {
    key: 'ebay',
    name: 'eBay',
    description: 'eBay commerce and marketplace data',
    category: 'commerce',
    authType: 'oauth',
    capabilities: ['account', 'listings', 'orders', 'revenue', 'metrics', 'sync'],
    supportsSync: true,
    supportsWebhooks: true,
    supportsCommerce: true,
    enabled: true,
    iconKey: 'ebay',
  },
  {
    key: 'instagram',
    name: 'Instagram',
    description: 'Meta Instagram business accounts and metrics',
    category: 'social',
    authType: 'oauth',
    capabilities: ['account', 'content', 'audience', 'metrics', 'sync'],
    supportsSync: true,
    supportsMetrics: true,
    supportsContent: true,
    enabled: true,
    iconKey: 'instagram',
  },
  {
    key: 'youtube',
    name: 'YouTube',
    description: 'YouTube channel and video metrics',
    category: 'video',
    authType: 'oauth',
    capabilities: ['account', 'content', 'audience', 'metrics', 'sync'],
    supportsSync: true,
    supportsMetrics: true,
    supportsContent: true,
    enabled: true,
    iconKey: 'youtube',
  },
  {
    key: 'website',
    name: 'Website',
    description: 'First-party website connectors and events',
    category: 'website',
    authType: 'none',
    capabilities: ['traffic', 'conversions', 'metrics', 'webhooks', 'sync'],
    supportsSync: true,
    supportsWebhooks: true,
    supportsMetrics: true,
    enabled: true,
    iconKey: 'website',
  },
  {
    key: 'stripe',
    name: 'Stripe',
    description: 'Payments and financial activity',
    category: 'payments',
    authType: 'oauth',
    capabilities: ['account', 'revenue', 'orders', 'metrics', 'webhooks'],
    supportsSync: false,
    supportsWebhooks: true,
    supportsMetrics: true,
    enabled: true,
    iconKey: 'stripe',
  },

  // future providers (disabled by default)
  {
    key: 'google_analytics',
    name: 'Google Analytics',
    category: 'analytics',
    authType: 'oauth',
    description: 'GA data',
    capabilities: ['metrics', 'traffic'],
    enabled: false,
    iconKey: 'google_analytics',
  } as IntegrationProvider,
  {
    key: 'google_search_console',
    name: 'Google Search Console',
    category: 'analytics',
    authType: 'oauth',
    description: 'Search Console',
    capabilities: ['metrics', 'traffic'],
    enabled: false,
    iconKey: 'google_search_console',
  } as IntegrationProvider,
  {
    key: 'tiktok',
    name: 'TikTok',
    category: 'social',
    authType: 'oauth',
    description: 'TikTok',
    capabilities: ['content', 'audience', 'metrics'],
    enabled: false,
    iconKey: 'tiktok',
  } as IntegrationProvider,
  {
    key: 'facebook',
    name: 'Facebook',
    category: 'social',
    authType: 'oauth',
    description: 'Facebook',
    capabilities: ['content', 'audience', 'metrics'],
    enabled: false,
    iconKey: 'facebook',
  } as IntegrationProvider,
  {
    key: 'linkedin',
    name: 'LinkedIn',
    category: 'social',
    authType: 'oauth',
    description: 'LinkedIn',
    capabilities: ['content', 'audience', 'metrics'],
    enabled: false,
    iconKey: 'linkedin',
  } as IntegrationProvider,
  {
    key: 'github',
    name: 'GitHub',
    category: 'analytics',
    authType: 'oauth',
    description: 'GitHub',
    capabilities: ['metrics'],
    enabled: false,
    iconKey: 'github',
  } as IntegrationProvider,
  {
    key: 'microsoft',
    name: 'Microsoft',
    category: 'analytics',
    authType: 'oauth',
    description: 'Microsoft',
    capabilities: ['metrics'],
    enabled: false,
    iconKey: 'microsoft',
  } as IntegrationProvider,
  {
    key: 'gmail',
    name: 'Gmail',
    category: 'analytics',
    authType: 'oauth',
    description: 'Gmail',
    capabilities: ['metrics'],
    enabled: false,
    iconKey: 'gmail',
  } as IntegrationProvider,
];

export function getProvider(key: IntegrationProvider['key']) {
  return providers.find((p) => p.key === key) || null;
}

export function listProviders() {
  return providers;
}
